---
title: "힐베르트 공간과 브라켓 표기법"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---


## 힐베르트 공간 {#sec-part1_hilbert_space}

양자역학은 힐베르트 공간에서 기술된다. **힐베르트 공간(Hilbert space)**은 우리가 익숙한 유한차원 내적 벡터공간의 성질을 가지고 있는 무한차원 복소 벡터공간을 말한다. 보통 양자역학에서는 유한차원이든 무한차원이든 양자역학을 기술하는 수학적 공간을 힐베르트 공간이라고 한다.

힐베르트 공간은 벡터공간이며 따라서 힐베르트 공간의 원소는 벡터이다. 역사적, 실용적 이유로 양자역학에서의 표기법은 보통 수학에서의 표기법과는 다른 브라켓 표기법을 사용하며 대표적으로 벡터는 $|a\rangle$ 과 같이 $|\,\rangle$ 형태로 표기하며, 선형연산자는 $\hat{L}$ 과 같이 문자 위에 $\hat{~}$ 기호를 씌워 표기하거나 단지 $L$ 과 같이 쓰기도 한다. 양자역학에서의 상태는 수학적으로 힐베르트 공간의 벡터이다. 

</br>

## 브라켓 표기법 {#sec-part1_braket_notation}

브라켓 표기법은 양자역학을 기술하는 표기법으로 폴 디랙에 의해 고안되었다. 양자역학은 힐베르트 공간에서 기술되며 실용적인 이유로 수학자들의 표기법이 아닌 P.A.M Dirac 에 의해 고안된 브라켓 표기법을 사용하게 되었다. 

수학에서는 두 벡터 $a,\,b$ 의 내적을 보통 $(a,\,b)$ 나 $\langle a,\, b\rangle$ 로 표기하며 $\langle a,\,b\rangle$ 는 실제로는 (1) 벡터 $a$ 와 (2) $$b$ 에 대한 쌍대벡터의 연산이다. 복소벡터공간에서 벡터 $a_1,\,a_2$ 와 스칼라 $c_1,\,c_2$ 에 대해

$$
\begin{aligned}
( c_1 a_1 + c_2 a_2,\, b ) &= c_1 ( a_1,\,b ) + c_2 ( a_2,\, b), \\
( b,\,c_1a_1+c_2a_2 ) &= \overline{c_1} ( b,\, a_1 ) + \overline{c_2} ( b,\, a_2). \\
\end{aligned}
$$

이 성립한다. $(\, , \,)$ 대신 $\langle\, , \, \rangle$ 을 사용하기도 하다. 

양자역학의 브라켓 표기법은 다음의 규칙을 따른다.

::: {.callout-important icon="false"}

#### 브라켓 표기법

1. 벡터는 $|\phi\rangle$ 과 같이 표기하며 **캣(ket)** 라고 한다. $|\phi\rangle$ 에 대한 스칼라 $c$ 곱은 $c|\phi\rangle$ 과 같이 표기한다. 선형결합은 $c_1|\phi_1\rangle + c_2|\phi_2\rangle + \cdots$ 와 같이 표현한다.

2. 연산자 $A$ 에 대한 $|\phi\rangle$ 의 선형변환은 $A|\phi\rangle$ 로 표기한다. 
  
3. $|\phi \rangle$ 에 대한 dual vector 를 $\langle \phi|$ 로 표기하며 **브라(bra)** 이라고 한다. $\langle \phi| = | \phi\rangle^\dagger$ 로 쓰기도 한다. 벡터 $|\phi\rangle$ 과 $|\psi\rangle$ 에 대한 내적은 $\langle \psi | \phi \rangle$ 로 표기한다. 브라와 캣을 합쳐서 **브라켓(bra-ket)** 이라고 한다. 내적에 대해 $\langle \phi |\psi \rangle = \overline{\langle \psi|\phi \rangle}$ 이다. 

4. 따라서 $(c_1 |\psi_1\rangle + c_2|\psi_2)^\dagger = \overline{c_1}\langle \psi_1| + \overline{c_2}\langle \psi_2| = \langle \psi_1| \overline{c_1} +\langle \psi_1| \overline{c}_2$ 이다. 이로부터 다음이 성립한다.  
$$
\begin{aligned}
\langle \psi | \left(c_1  |\phi_1\rangle + c_2 | \phi_2\rangle\right) &= c_1 \langle \psi|\phi_1\rangle + c_2 \langle \psi|\phi_2\rangle, \\
(c_1 |\psi_1\rangle + c_2 |\psi_2\rangle)^\dagger| \phi \rangle & = \overline{c_1}\langle \psi_1|\phi \rangle + \overline{c_2}\langle\psi_2 |\phi\rangle. 
\end{aligned}
$$


6. $\langle \psi | A |\phi \rangle = \langle \psi| (A| \phi \rangle)$ 을 의미한다. 즉 브라켓 사이의 선형연산자는 켓에 대한 선형연산자를 의미한다. 또한 $(A|\psi\rangle)^\dagger |\phi\rangle = \langle \psi|A^\dagger|\phi\rangle$ 이다. 

:::


<br>

양자역학에서 캣은 양자상태를 표현하는 벡터이며 $0$ 이 아닌 $c\in \mathbb{F}$ 에 대해 $c|\psi \rangle$ 과 $|\psi\rangle$ 을 동일하다고 간주한다. 일반적으로 ket 은 $\langle \phi | \phi \rangle =1$ 인 정규화된벡터를 의미하는 경우가 많다. 또한 유한차원 복소벡터공간에서 양자상태를 표현한다면 $|\phi\rangle$ 을 열벡터로, $\langle \psi |$ 를 행벡터로 표현한다. 브라켓 표기법을 사용하는 이유를 요약하면 다음과 같다.

1. 양자 상태 표현의 편의성 : 브라켓으로 벡터를 표현할 때의 가장 큰 장점은 양자상태를 표현할 때 수학적인 표기법보다 편하다는 것이다. 예를 들어 양자수 3개로 정의되는 상태에 대해 $|abc\rangle$ 과 같이 세개의 숫자를 쓴 다음에 캣으로 묶어버리는 것으로 양자상태를 표현할 수 있다. 수소원자의 경우 주양자수 $n=2$, 궤도양자수 $l=1$, 자기양자수 $m=0$ 인 상태를 $|nlm\rangle$ 표기법을 사용하여 $|210\rangle$ 으로 표기할 수있다. 또한 내적에서 사용되는 쌍대기저를 독립적인 브라 표기법으로 $\langle 210 |$ 와 같이 표현 할 수 있다. 만약 브라켓 표기법 없이 사용한다면 $|210\rangle$ 상태를 $\Psi_{210}$ 이나 $\Phi^2_{10}$ 과 같이 표현해야 할 것이다. 

2. 연산자와 벡터의 분리 : $\langle\phi | \hat{A} |\psi\rangle$ 형식이기 때문에 연산자의 연산을 브라와 캣 사이의 공간에서 수행 할 수 있는데 이는 수식표기가 좀 더 깔끔해진다.

3. 앞으로 다루겠지만 projection operator $|\phi\rangle\langle \psi|$ 와 내적 $\langle \psi|\phi\rangle$ 의 구분이 명확해진다. 벡터를 사용한다면 $\boldsymbol{\psi} \boldsymbol{\phi}^\ast$ 와 $\boldsymbol{\psi}^\ast\boldsymbol{\phi}$ 와 같이 구분하기 힘들다. 

</br>

### 영벡터

원래 벡터공간은 영벡터를 항상 포함하며 수학에서는 $0$, $\boldsymbol{0}$ 혹은 $\overrightarrow{0}$ 과 같이 표기하며 벡터의 덧셈에 대한 항등원이다. 그러나 브라켓 표기법으로 $|0\rangle$ 은 어떤 $0$ 인 양자상태나 인덱스를 표기하는데 사용 될 수 있으며 이를 섞어 사용하는 것은 혼란을 준다. 따라서 여기서는 $|\varnothing\rangle$ 로 영벡터를 표현하기로 하자. 

</br>

### 에르미트 conjugate

행렬 $A$ 에 대한 hermite cojulgate $A^\dagger$ 는 $(A|\psi)^\dagger |\phi\rangle = \rangle \psi |A^\dagger |\phi\rangle$ 을 만족하는 $A^\dagger$ 를 의미한다. $A^\dagger$ 역시 연산자이며 

$$
\langle \psi|A|\phi \rangle = \langle \psi| \left(A|\phi \rangle\right) = \left[(A|\phi\rangle)^\dagger |\psi\rangle \right]^\dagger = \overline{\langle \phi |A^\dagger |\psi\rangle}
$$

의 관계를 가진다. 


</br>

## 에르미트 연산자 {#sec-part1_hermitian_operator}

힐베르트 공간 $\mathscr{H}$ 에서 정의된 선형사상 $A:\mathscr{H} \to \mathscr{H}$ 를 **연산자(operator)** 라고 한다. 선형사상은 임의의 $|a\rangle,\, |b\rangle,\, c\in \mathbb{F}$ 에 대해

$$
A(|a\rangle + c|b\rangle) =  A|a\rangle + c(A|b\rangle)
$$

인 함수를 의미한다. 연산자 $A$ 에 대해 $(A|a\rangle)^\dagger = \langle a|A^\dagger$ 인 $A^\dagger$ 를 $A$ 에 대한 **Hermitian adjoint** 라고 한다. 

$A^\dagger = A$ 인 연산자를 에르미트 연산자라고 한다. 양자역학에서 에르미트 연산자는 매우 중요하며 특별히 다룰 가치가 있다. 에르미트 연산자의 기본적인 성질은 다음과 같다. 

::: {.callout-note icon="false"}

#### 에르미트 연산자의 기본적인 성질

&emsp; **1.** 에르미트 연산자의 고유값은 실수이다.

&emsp; **2.** 서로 다른 고유값을 갖는 에르미트 연산자의 고유벡터는 직교한다.

&emsp; **3.** 에르미트 연산자에 대한 교유벡터로 벡터공간의 정규직교기저를 구성 할 수 있다.

&emsp; **4.** 에르미트 연산자는 특정 기저에 대해 대각행렬로 표현 될 수 있다.

:::

</br>

### Completeness 와 degeneracy

$3$ 의 성질을 **completness** 라고 부른다. $\mathscr{H}$ 의 에르미트 연산자 $A$ 의 고유벡터로 이루어진 정규직교기저 $\{|a_1\rangle ,\, |a_2,\rangle,\ldots\}$ 를 생각하자. 임의의 $|\psi\rangle \in \mathscr{H}$ 에 대해 

$$
|\psi\rangle = \sum_i c_i |a_i\rangle =\sum_i |a_i\rangle \langle a_i |\psi\rangle = \left(\sum_i |a_i\rangle \langle a_i|\right) |\psi\rangle
$$

이므로

$$
\sum_i |a_i\rangle \langle a_i| = I
$$ {#eq-part1_completeness}


이어야 한다. 여기서 생각해 봐야 할 것은 에르미트 연산자의 선형독립인 고유벡터가 같은 고유값을 가질 수 있다는 것이다. 예를 들어

$$
A=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 2\end{bmatrix}
$$

는 고유값 $1$ 과 $2$ 를 갖는 에르미트 연산자이며 $\boldsymbol{e}_1$ 과 $\boldsymbol{e}_2$ 는 같은 고유값 $1$ 을 갖는 $A$ 의 고유벡터이다. 이렇게 같은 고유값을 갖는 선형 독립인 고유벡터가 있을 경우를 **degeneracy** 라고 한다. 우리는 degeneracy 가 있는 연산자에 대해 같은 고유값을 갖는 벡터의 집합은 $\mathscr{H}$ 의 부분공간을 이룬다는 것을 안다. 이것을 고유공간(eigenspace) 라고 하며 $\mathscr{H}$ 의 고유공간에 대해 정규직교기저를 구성할 수있다는 것을 안다. 

즉 $\mathscr{H}$ 에서 정의된 에르미트 연산자 $A$ 의 고유값이 $\lambda_1,\,\lambda_2,\ldots$ 일 때 $\lambda_i$ 에 대한 고유공간의 차원이 $1$ 이면 정규벡터 $|a_i\rangle$ 을 찾을 수 있으며, $\lambda_j$ 에 대한 고유공간이 2차원 이상일 때 이 고유공간의 정규직교기저 $\left| a_j^{(1)}\right\rangle,\, \left|a_j^{(2)}\right\rangle,\ldots$ 를 찾을 수 있다. 이 때, 

$$
\langle a_i^{(k)}|a_j^{(l)}\rangle = \delta_{ij}\delta_{kl}
$$

이 된다. 이렇게 이루어진 정규직교벡터의 집합 $\{a_i^{(k)}\}$ 는 $\mathscr{H}$ 의 정규직교기저를 이룬다.





</br>

### 행렬 표현

선형연산자 $L$ 는 벡터공간의 어떤 정규직교기저 $\{|a_1\rangle,\,|a_2\rangle,\ldots\}$ 에 대해 행렬로 표현 할 수 있다. 

$$
L = \sum_i \sum_j  |a_j\rangle \langle a_j|L|a_i\rangle \langle a_i| 
$$

이 때 $L_{ij}:=\langle a_j|L|a_i\rangle$ 로 이루어진 행렬을 연산지 $L$ 의 $\{|a_1\rangle,\,|a_2\rangle,\ldots\}$ 기저에 대한 에 대해 행렬 표현 이라고 하며, 둘 사이에 일대일 대응이 존재하기 때문에 굳이 구분하지 않고 연산자=행렬 이라고 표현하는 경우도 많다.

$L$ 이 에르미트 행렬인 경우 

$$
(L^\dagger)_{ij} = \langle a_j|L^\dagger|a_i\rangle = \langle a_j|L|a_i\rangle = 
$$

</br>


## Compatible operator

::: {.callout-note appearance="minimal"}

::: {#def-part1_commutator_of_operators}

#### Commutator 

두 연산자 $L,\,M$ 에 대해 

$$
[L,\,M] := LM-ML
$$ {#eq-part1_commutators}

을 두 연산자에 대한 **commutator** 라고 한다. $[L,\,M]=0$ 이면 두 연산자는 **compatible** 하다고 한다.

:::
:::

</br>




::: {#prp-part1_uncertainty_1}

힐베르트 공간 $\mathscr{H}$ 에서 정의된 두 에르미트 연산자 $L,\,M$ 에 대해 다음은 동치이다.

&emsp; ($1$) $[L,\,M]= 0$.

&emsp; ($2$) $L$ 과 $M$ 에 대해 동시에 모두 고유벡터인 벡터로 이루어진 $\mathscr{H}$ 의 기저가 존재한다.
:::

::: {.proof}

($1 \implies 2$) $L$ 과 $M$ 이 에르미트 연산자이므로 각각의 고유상태로 이루어진 $\mathscr{H}$ 의 기저가 존재한다. 고유값 $l_i$ 인 $L$ 의 고유상태를 $|l_i\rangle$ 로 표기하자. 

$$
|\varnothing\rangle=[L,\,M]|l_i\rangle = (LM- M l_i) |l_i\rangle = (L- l_i) M|l_i\rangle
$$

이므로 $M|l_i\rangle$ 는 고유값 $l_i$ 를 갖는 $L$ 의 고유상태이다. $M$ 역시 에르미트 연산자이므로 

$$
M|l_i\rangle = \sum_j m_j|l_i m_j\rangle
$$

로 쓸 수 있다. 따라서 $\mathscr{H}$ 는 $\{|l_i m_j\rangle \}$ 를 기저로 갖는다.

($2 \implies 1$) $L$ 과 $M$ 에 대해 각각 $l,\,m$ 의 고유값을 갖는 동시에 고유상태인 기저를 $|lm\rangle$ 라고 하면 

$$
[L,\,M]|lm\rangle = LM|lm\rangle - ML|lm\rangle = (lm-lm)|lm\rangle = |\varnothing\rangle
$$

이므로 $[L,\,M] = \hat{0}$ 이다. $\square$
:::

</br>


@prp-part1_uncertainty_1 은 양자역학이 degeneracy 를 해결하는 방법을 말해준다. 어떤 에르미트 연산자 $L$ 에 대하나 고유상태가 degenrated 되어 있을 경우 $L$ 과 compatible 한 연산자 $M$ 을 찾으며, 운이 좋다면 $L$ 의 degenerated 된 고유공간를 $M$ 의 고유상태로 분해 할 수 있다. $L,\,M$ 이 compatible 하므로 이 분해된 고유공간 역시 $L$ 의 고유공간이므로 우리의 목적을 해치지 않는다. 만약 $L$ 에 대해 compatible 한 모든 연산자에 대해 분해되지 않는 2차원 이상의 고유공간이 존재한다면 이것은 자연이 우리에게 허용하지 않은 구분이다. 그러나 실제적인 경우에는 이런것은 존재하기 힘들다.(@Sakurai1994)


</br>

## 무한차원에 대해


### 디랙 델타함수 {#sec-part_dirac_delta_function}

양자역학에서 위치 $x$ 나 운동량 $p$ 와 같은 연속적인 값을 다루는데는 디렉 댈타 함수 $\delta (x)$ 가 필수적이다.

::: {.callout-note appearance="minimal"}

::: {#def-part1_dirac_delta_function}

#### 1차원 디랙 델타 함수

1차원 디렉 델타 함수 $\delta(x)$ 는 아래의 성질을 만족하는 함수이다.

&emsp; ($1$) $\delta (x) = \left\{ \begin{array}{ll} +\infty \qquad & ;\text{x=0}.\\ 0 &;\text{oterwise}.  \end{array}\right.$

&emsp; ($2$) $\displaystyle \int_{-\infty}^\infty f(x)\, \delta (x) \, dx = f(0)$.

:::

:::


여기서는 참고를 위해 디랙 델타함수의 성질에 대해 증명 없이 기술하기로 한다.

</br>

::: {#prp-part1_properties_of_dirac_delta_function}

#### 디랙 델타 함수의 성질

디랙 델타 함수 $\delta(x)$ 는 아래의 성질을 만족한다.

&emsp; ($1$) $\delta (-x) = \delta (x)$,

&emsp; ($2$) $\displaystyle \int f(x) \delta (x-x')\, dx = f(x')$,

&emsp; ($3$) $\delta (ax) = \dfrac{1}{|a|}\delta (x)$,

&emsp; ($4$) $g(x)=0$ 의 해 $\{x_i\}$ 에 대해 모든 $x_i$ 에서 $g(x_i)\ne 0$ 일 때 $\displaystyle \delta (g(x)) = \sum_{i} \dfrac{\delta(x-x_i)}{|g'(x_i)|}$,

&emsp; ($5$) $\displaystyle \int f(x)\, \delta'(x)\, dx = f'(0)$, 

&emsp; ($6$) $x\,\delta'(x) = - \delta(x)$

&emsp; ($7$) $\displaystyle \dfrac{1}{2\pi}\int_{-\infty}^\infty e^{ikx}\, dk = \delta (x)$. 

:::

</br>

### 무한차원 벡터공간에서의 연속적인 변수에 대한 기술

$$
\sum_i |a_i\rangle \langle a_i|\psi\rangle \longrightarrow \int | x\rangle \langle  x|\psi\rangle \, dx
$$

$$
\langle x|x'\rangle = \delta(x-x')
$$