---
title: "대칭"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

## 고전역학의 대칭

우리는 고전역학의 해밀토니안 $\mathcal{H}$ 에 대해 다음이 성립한다는 것을 안다.

($1$) 동역학 변수 $g(q,\,p)$ 에 의한 infinitesimal canonical transformation 에 대해 해밀토니안이 변하지 않으면 $g$ 는 보존된다.

($2$) $\mathcal{H}$ 가 불변인 canonical transformation 에 의한 운동방정식의 해의 변환은 역시 운동방정식의 해이다.

</br>

## 양자 이론에서의 translational invariance

양자역학에서 translational invariance, 즉 어떤 translation 에 대한 해밀토니안 $H$ 의 invariance 를 어떻게 정의할 것인가? 양자역학에서는 임의의 상태에 대한 어떤 위치라는 것도 정의가 되지 않으며, 따라서 infinetsimal translation 에 대한 해밀토니안의 불변성도 정의 할 수 없다. 그러나 고전역학에서 정의된 어떤 양은 양자역학에서의 기대값에 상응하도록 되어있는 경우가 많다는 것을 고려하면, 양자역학에서의 translational invariance 는 (그것을 생각해야 한다면) 경로의 기대값에 대한 infinitesimal transformation 에 대한 것이어야 할 것이다. 즉, 

$$
\begin{aligned}
\langle X \rangle &\to \langle X\rangle + \varepsilon,\\[0.3em]
\langle P \rangle &\to \langle P \rangle
\end{aligned}
$$ {#eq-part2_infinitesimal_translation}

에 대한 것이다. Infinitesimal translation $T_{\varepsilon}$ 에 의해 상태벡터 $|\Psi \rangle$ 이 ㅣ변한 상태를 $|\Psi_\varepsilon\rangle$ 이라고 하자. 즉

$$
T_{\varepsilon}|\Psi\rangle = |\Psi_\varepsilon\rangle
$$

에 대해

$$
\begin{aligned}
\langle \Psi_\varepsilon|X|\Psi_\varepsilon \rangle &= \langle \Psi|X|\Psi\rangle + \varepsilon,\\
\langle \Psi_\varepsilon|P|\Psi_\varepsilon \rangle &= \langle \Psi|P|\Psi\rangle 
\end{aligned}
$$

라는 의미이다. 이것은 active transformation 에서의 관점이다. 즉 변환은 상태벡터를 변화시킨다. 이와 동등하지만 다른 passive transformation 은 연산자 자체를 다음과 같이 변화시킨다. 
$$
\begin{aligned}
X & \to T^\dagger_\varepsilon XT_{\varepsilon} = X+\varepsilon I,\\
P & \to T^\dagger_\varepsilon PT_{\varepsilon} = P
\end{aligned}
$$

이라고 하자. 여기에 대해 

$$
\begin{aligned}
\langle \Psi|T^\dagger_\varepsilon X T_{\varepsilon} |\Psi\rangle &= \langle \Psi |X|\Psi\rangle + \varepsilon, \\[0.3em]
\langle \Psi|T^\dagger_\varepsilon P T_{\varepsilon} |\Psi\rangle &= \langle \Psi |P|\Psi\rangle
\end{aligned}
$$

이 성립한다. 이미 알겠지만 능동적 변환과 수동적 변환은 동일한 현상에 대한 다른 수학적 표현법일 따름이다. 이제 우리는 $T_\varepsilon$ 을 구해보도록 하자. 일단 active transformation 의 관점을 따르기로 한다. 우선 $X$ 기저에서 $|x\rangle$ 상태에 있는 입자에 대해


$$
T_{\varepsilon}|x\rangle = |x+\varepsilon\rangle
$$

라고 할 수 있다. $|x\rangle$ 는 $X$ 에 대한 정규직교기저이며 $|x+\varepsilon\rangle$ 도 그러하다. 즉 $T_\varepsilon$ 은 유니타리 연산자이다. 이제 $|\Psi_\varepsilon \rangle = T_\varepsilon |\Psi\rangle$ 을 생각해보자. 

$$
\begin{aligned}
|\Psi_\varepsilon\rangle = T_{\varepsilon}|\Psi\rangle &= T_{\varepsilon} \int_{-\infty}^\infty |x\rangle \langle x|\Psi\rangle\, dx = \int_{-\infty}^\infty |x+\varepsilon\rangle \langle x|\Psi\rangle \,dx , \\
&= \int_{-\infty}^\infty |x'\rangle \langle x'-\varepsilon|\Psi\rangle \, dx'
\end{aligned}
$$

이므로 

$$
\Psi_\varepsilon (x) = \langle x|T_{\varepsilon}|\Psi\rangle = \int_{-\infty}^\infty \langle x|x'\rangle \langle x'-\varepsilon|\Psi\rangle\, dx' = \Psi(x-\varepsilon)
$$

이다. 즉 파동함수 $\psi (x) = \langle x|\psi\rangle$ 에 대해 $\psi_\varepsilon (x) = \langle x|T_\varepsilon |\psi\rangle = \psi(x-\varepsilon)$ 이며 이것은 파동함수의 translation 을 의미한다는 것을 알 수 있다. 또한, 

$$
\begin{aligned}
\langle \Psi_\varepsilon|P|\Psi_\varepsilon\rangle &= \int_{-\infty}^\infty \Psi_\varepsilon^\ast(x) \left(-i\hbar \dfrac{d}{dx}\right)\Psi_\varepsilon(x)\, dx \\
&= \int_\infty^\infty\Psi^\ast(x) \left(-i\hbar \dfrac{d}{dx}\right)\Psi (x)\, dx = \langle \Psi |P|\Psi\rangle
\end{aligned}
$$

이다. 즉, 아마 예상했던 바와 같이 translation 에 대해 운동량의 기대값은 변하지 않는다. 

여기서 한가지 짚고 넘어가야 할 것이 있다. 고전역학에서는 $x$ 와 $p$ 는 독립적이며 고전역학에서의 translation 은 

$$
\begin{aligned}
x &\to x+\varepsilon, \\
p &\to p
\end{aligned}
$$

라는 독립적인 두 변환이 동시에 성립할때를 말한다. 그러나 양자역학에서는 $|x\rangle \to |x+\varepsilon\rangle$ 변환만으로 translation 변환이 정해지는 것처럼 보인다. 어떤 차이가 있을까? 한가지 답은 $T_{\varepsilon}|x\rangle = |x+\varepsilon\rangle$ 이외의 것도 가능하다는 것이다. 예를 들어 어떤 $\lim_{x\to 0}g(x) = 0$ 인 미분가능함수 $g(x)$ 에 대해

$$
T_{\varepsilon} |x\rangle = e^{i\varepsilon g(x)/\hbar}|x+\varepsilon\rangle
$$

라고 해 보자. 이 때

$$
\begin{aligned}
\langle x|T_{\varepsilon} |\Psi\rangle &= \int \langle x|T_{\varepsilon}|x'\rangle  \langle x'|\Psi\rangle \, dx' \\
&= \int \langle x|e^{i\varepsilon g(x')/\hbar} |x'+\varepsilon\rangle \langle x'|\Psi\rangle \, dx'  \\
&=\int \delta(x-x'-\varepsilon) e^{i\varepsilon g(x')/\hbar} \, \Psi(x')\, dx' = e^{i\varepsilon g(x-\varepsilon)} \Psi(x-\varepsilon)
\end{aligned}
$$

이다. 이를 이용하면 

$$
\begin{aligned}
\langle \Psi|T^\dagger_{\varepsilon} X T_{\varepsilon}|\Psi\rangle &=\int \Psi^\ast(x-\varepsilon) X \Psi (x-\varepsilon)\, dx = \langle \Psi|X|\Psi \rangle +\varepsilon
\end{aligned}
$$

이며, 

$$
\begin{aligned}
\langle \Psi|T^\dagger_{\varepsilon} P T_{\varepsilon}|\Psi\rangle &= \int e^{-i \varepsilon g(x-\varepsilon)/\hbar} \Psi^\ast (x-\varepsilon) \left(-i\hbar \dfrac{d}{dx}\right) e^{i\varepsilon g(x-\varepsilon)/\hbar} \Psi(x-\varepsilon)\, dx \\
&= \int \varepsilon g'(x-\varepsilon) \Psi^\ast (x-\varepsilon)\Psi(x-\varepsilon)\, dx  + \langle \Psi |P |\Psi\rangle  \\
&= \langle \Psi |P |\Psi \rangle + \varepsilon \langle g'(x) \rangle
\end{aligned}
$$

이다. 즉 우리가 $T_\varepsilon |x\rangle = |x+\varepsilon\rangle$ 을 선택한 것은 $\langle X\rangle \to \langle X\rangle + \varepsilon,\, \langle P \rangle \to \langle P \rangle$ 인 변환을 선택한 것이다. 

이제 $X$ 기저에 대한 $T_\varepsilon$ 을 정의했으므로 $T_\varepsilon$ 에 대한 몇가지 성질을 알아보자.

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">
::: {#exr-part3_properties_of_translation_operator}

Infinitesimal translation operator $T_\varepsilon$ 에 대해 다음을 보여라.

&emsp; ($1$) $T_\varepsilon$ 은 unitery 이다. 

&emsp; ($2$) $T_{\varepsilon_1} T_{\varepsilon_2} = T_{\varepsilon_1+ \varepsilon_2}$ 이다.

&emsp; ($3$) $T^\dagger_\varepsilon = T_{-\varepsilon}$ 이다.

:::


::: {.proof}

($1$) $\langle \Psi | \Psi\rangle = \langle \Psi|T^\dagger_\varepsilon T |\Psi\rangle$ 이면 $T_\varepsilon$ 은 uniatary 이다.

$$
\langle T_\varepsilon \Psi | T_\varepsilon \Psi\rangle = \int_{-\infty}^\infty \Psi^\ast(x-\varepsilon) \Psi(x-\varepsilon)\, dx = \int_{-\infty}^\infty \Psi^\ast(x) \Psi(x)\, dx = \langle \Psi|\Psi\rangle
$$

($2$) $T_{\varepsilon_1}T_{\varepsilon_2}|x\rangle = T_{\varepsilon_1}|x+\varepsilon_1\rangle = |x+\varepsilon_1+\varepsilon_2\rangle = T_{\varepsilon_1+\varepsilon_2}|x\rangle$

($3$) $T$ 가 unitary 이므로 $T^\dagger_\varepsilon T_\varepsilon = I$ 이며 ($2$) 로 부터 $T^\dagger_\varepsilon = T_{-\varepsilon}$ 이다. $\square$

:::

</div></br>

Translation 을 선택했으므로 우리는 translational invariance 를 정의 할 수 있다. 즉 $|\Psi_\varepsilon\rangle = T_\varepsilon|\Psi\rangle$ 에 대해

$$
\langle \Psi| H |\Psi\rangle = \langle \Psi_\varepsilon | H |\Psi_\varepsilon \rangle
$$

일 때 해밀토니안 $H$ 가 translatinal invariance 라고 한다. 이제 $T_{\varepsilon}$ 을 명확하게 구성해 보자. $\varepsilon=0$ 일 때 $T_{\varepsilon} = I$ 이므로 $\varepsilon$ 의 1차항까지 전개하여

$$
T_{\varepsilon}= I-\dfrac{i\varepsilon}{\hbar}G
$$ {#eq-part2_translation_operator}

라고 하자. @eq-part2_translation_operator 는 근사식이며 많은 계산에서 $\varepsilon$ 에 대한 1차식가지만의 결과가 사용되기 때문에 편리하다. 이 때 $G$ 는 translation 의 generator 라고 한다. $G$ 가 애르미트 연산자임은 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-shankar_11_2_2}
#### Shankar 11.2.2

$T_\varepsilon$ 이 유니타리 임을 이용하여 @eq-part2_translation_operator 의 $G$ 는 에르미트 임을 보여라.

:::

::: {.solution}

$T^\dagger_{\varepsilon} T_{\varepsilon}= I$ 이므로,

$$
T^\dagger T = I - \dfrac{i\varepsilon}{\hbar}(G-G^\dagger) + o(\varepsilon^2) = I
$$

이다. 따라서 $G=G^\dagger$ 이다.

:::

</div></br>

이제 $G$ 연산자를 구해보자. $\langle x|T_{\varepsilon} |\Psi\rangle = \Psi(x-\varepsilon)$ 이므로 양변을 order of $\varepsilon$ 까지 전개하면 

$$
\Psi(x) - \dfrac{i\varepsilon}{\hbar} \langle x|G|\Psi\rangle = \Psi (x) - \varepsilon\dfrac{d}{dx}\Psi(x)
$$

이다. 즉, 

$$
\langle x|G|\Psi \rangle = -i\hbar \dfrac{d}{dx}\Psi(x)
$$

이므로 $G=P$ 이고 

$$
T_{\varepsilon} = I - \dfrac{i\varepsilon}{h}P
$$

임을 알 수 있다. 즉 양자역학에서도 고전역학에서와 마찬가지로 운동량은 infinitesimal translation transformation 의 generator 이다. 

</br>

이제 고전역학에서와 같이 translational invariance 로 부터 운동량이 보존된다는 것을 보이자.

$$
\begin{aligned}
\langle \Psi_\varepsilon | H | \Psi_\varepsilon \rangle &= \langle T_\varepsilon \Psi | H | T_\varepsilon \Psi\rangle \\
&= \langle \Psi | \left(I + \dfrac{i\varepsilon}{\hbar}P\right) H \left(I - \dfrac{i\varepsilon}{\hbar}P\right) |\Psi \rangle  \\
&= \langle \Psi | H |\Psi \rangle + \dfrac{i\varepsilon}{\hbar} + \dfrac{i\varepsilon}{\hbar} \langle \Psi | [P,\, H]|\Psi \rangle
\end{aligned}
$$

이므로 $\Psi_\varepsilon| H |\Psi_\varepsilon \rangle = \langle \Psi | H |\Psi \rangle$ 로부터 $[P,\, H] = 0$ 을 얻는다. 즉 $\langle \dot{P}\rangle = 0$ 이므로 $P$ 는 보존된다.

</br>

### Passive transform 으로 본 translation

Translation $T_\varepsilon$ 이 연산자에 적용된다면

$$
T_\varepsilon^\dagger XT_\varepsilon = X + \varepsilon I,\qquad T^\dagger_\varepsilon P T = P
$$ {#eq-part2_transilation_in_passive_transform}


이다. $T^\dagger_\varepsilon X T_\varepsilon$ 은 원점이 $\varepsilon$ 만큼 이동되었을 때의 위치연산자이다. 이것을 다시

$$
T_\varepsilon = I - \dfrac{i\varepsilon}{\hbar}G
$$ {#eq-part2_translation_form_2}

라고 쓰자. @eq-part2_transilation_in_passive_transform 와 @eq-part2_translation_form_2, 그리고 $G^\dagger = G$ 로부터

$$
X+\varepsilon I = \left(I + \dfrac{i\varepsilon}{\hbar}G\right)X\left(I - \dfrac{i\varepsilon}{\hbar}G\right) = X - \dfrac{i\varepsilon}{\hbar} [X,\,G] + o(\varepsilon^2)
$$

를 얻는다. 즉 $[X,\,G] = i\hbar I$ 이므로 우리는 

$$
G=P+f(X)
$$ {#eq-part2_form_of_G}

 라는 것을 알 수 있다. 또한 $T^\dagger_\varepsilon P T = P$ 로부터

$$
P = P - \dfrac{i\varepsilon}{\hbar}[P,\,G]
$$

이므로 $[P,\,G] = 0$ 임을 알 수 있다. 그렇다면 $G=P+\text{const}$ 형태이며, @eq-part2_form_of_G 에서 $f(X) = \text{const}$ 임을 알 수 있으며, 우리는 상수항을 $0$ 으로 선택하여

$$
T_\varepsilon = I - \dfrac{i\varepsilon}{h} P
$$

라고 할 수 있다.

이제 일반적인 $X,\, P$ 의 power series 로 표현 될 수 있는 연산자 $\Omega (X,\,P)$ 에 Unitary transform $U$ 이 적용 될 경우 ($U^\dagger U = I$)

$$
U^\dagger \Omega (X,\,P) U = \Omega (U^\dagger XU,\, U^\dagger PU)
$$

이 성립한다는 것을 쉽게 알 수 있다. 

</br>

### 고전역학의 정준변환과 양자역학의 unitary 변환

Passive transformation 관점은 고전역학에서의 동역학 변수를 다루는 것과 비슷하기 대문에 양자역학과 고전역학을 비교하는데 유리함이 있다. 실제로 고전역학의 정준변환 (canonical transformation) 과 양자역학의 unitary 변환 사이에는 밀접한 관련이 있다. 이제 $\delta X$ 와 $\delta P$ 를 다음과 같이 정의하자.

$$
\begin{aligned}
\delta X &:= T^\dagger_\varepsilon XT_\varepsilon -X,\\
\delta P &:= T^\dagger_\varepsilon P T_\varepsilon - P.
\end{aligned}
$$


우리는 이미 @eq-part2_transilation_in_passive_transform 로부터 다음을 안다.

$$
\delta X = \varepsilon I,\qquad \delta P = 0.
$$

반면에 $T_\varepsilon = I - \dfrac{i\varepsilon}{\hbar} P$ 라는 근사식을 사용한다면 아래의 결과를 얻는다.

$$
\delta X = -\dfrac{i\varepsilon}{\hbar}[X,\,P] = \varepsilon  I,\qquad \delta P = -\dfrac{i\varepsilon}{\hbar}[P,\,P] = 0
$$

이것을 일반적인 동역학 변수 $\Omega(X,\,P)$ 까지 확장해보면 다음을 얻는다.

$$
\delta \Omega (X,\,P) = \Omega(X+\varepsilon I,\, P) - \Omega (X,\,P) = T_\varepsilon^\dagger \Omega T_\varepsilon - \Omega = -\dfrac{i\varepsilon}{\hbar}[\Omega,\,P]
$$

위의 두 식을 $p$ 에 의해 generated 되는 정준변환과 비교해보자. 

$$
\delta x = \varepsilon \{ x,\,p\} = \varepsilon,\qquad \delta p = \varepsilon \{p,\,p\} = 0, \qquad \delta \omega = \varepsilon \{\omega,\, p\} 
$$


만약 해밀토니안이 translation 에 대해 불변이라면, 즉

$$
\delta H = -\dfrac{i\varepsilon}{\hbar}[H,\, P] =0
$$


이라면 $[H,\,P]=0$ 이며, 띠라서 에렌페스트 정리로부터 $\langle \dot{P}\rangle = 0$ 을 얻는다. 고전적으로는

$$
\delta \mathcal{H} = \varepsilon \{\mathcal{H},\, p\} = 0
$$

으로부터 $\dot{p} = \{p,\, \mathcal{H}\} = 0$ 을 얻은 것이다. 이것을 일반화 시켜 보자면 고전역학에서 $g(x,\,p)$ 에 의해 generated 되는 infinitesimal 정준 변환

$$
\delta \omega = \varepsilon \{\omega,\, g\}
$$

에 대한 양자역학적인 결과는 infinitesimal unitary transform $U_G(\varepsilon) = I - i\varepsilon G/\hbar$ 에 대해

$$
\delta \Omega = -\dfrac{i\varepsilon}{\hbar} [\Omega,\, G]
$$

이다. 



### 연습문제

