---
title: "힐베르트 공간과 브라켓 표기법"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../latexmacros.qmd >}}

## 힐베르트 공간 {#sec-CHM_hilbert_space}

양자역학은 힐베르트 공간, 정확히 말하면 분리가능한 힐베르트 공간에서 기술된다. **힐베르트 공간(Hilbert space)**은 우리가 익숙한 유한차원 내적 벡터공간의 성질을 가지고 있는 무한차원 복소 벡터공간이라고 요약 할 수 있다. 

힐베르트 공간은 벡터공간이며 따라서 힐베르트 공간의 원소는 벡터이다. 역사적, 실용적 이유로 양자역학에서의 표기법은 보통 수학에서의 표기법과는 다른 브라켓 표기법을 사용하며 대표적으로 벡터는 $|a\rangle$ 과 같이 $|\,\rangle$ 형태로 표기하며, 선형연산자는 $\hat{L}$ 과 같이 문자 위에 $\hat{~}$ 기호를 씌워 표기하거나 단지 $L$ 과 같이 쓰기도 한다. 양자역학에서의 상태는 수학적으로 힐베르트 공간의 벡터이다. 

</br>

## 브라켓 표기법 {#sec-CHM_braket_notation}

브라켓 표기법은 양자역학을 기술하는 표기법으로 폴 디랙(P. A. M. Dirac) 에 의해 고안되으며 디랙 표기법, 혹은 브라켓 표기법이라고 불린다. 

수학에서는 두 벡터 $u,\,v$ 의 내적을 보통 $(u,\,v)$ 나 $\langle u,\, v\rangle$ 로 표기한다. 복소내적벡터공간에서는 벡터 $v_1,\,a_2$ 와 스칼라 $c_1,\,c_2$ 에 대해

$$
\begin{aligned}
( c_1 a_1 + c_2 a_2,\, b ) &= c_1 ( a_1,\,b ) + c_2 ( a_2,\, b), \\
( b,\,c_1a_1+c_2a_2 ) &= \overline{c_1} ( b,\, a_1 ) + \overline{c_2} ( b,\, a_2), \\
(u,\,v) &= \overline{(v,\,u)}.
\end{aligned}
$$

이 성립하도록 내적 기호 $(\, , \,)$ 혹은 $\langle\, , \, \rangle$ 를 정의한다. 그러나 양자역학의 표기법은 이와는 좀 다른 규칙을 적용한다.



::: {.callout-important icon="false"}

#### 브라켓 표기법

1. 벡터는 $|\phi\rangle$ 과 같이 표기하며 **캣(ket)** 라고 한다. $|\phi\rangle$ 에 대한 스칼라 $c$ 곱은 $c|\phi\rangle$ 과 같이 표기한다. 선형결합은 $c_1|\phi_1\rangle + c_2|\phi_2\rangle + \cdots$ 와 같이 표현한다.

2. 연산자 $A$ 에 대한 $|\phi\rangle$ 의 선형변환은 $A|\phi\rangle$ 로 표기한다. 
  
3. $|\phi \rangle$ 에 대한 dual vector 를 $\langle \phi|$ 로 표기하며 **브라(bra)** 이라고 한다. $\langle \phi| = | \phi\rangle^\dagger$ 로 쓰기도 한다. 벡터 $|\phi\rangle$ 과 $|\psi\rangle$ 에 대한 내적은 $\langle \psi | \phi \rangle$ 로 표기한다. 브라와 캣을 합쳐서 **브라켓(bracket)** 이라고 한다. 내적에 대해 $\langle \phi |\psi \rangle = \overline{\langle \psi|\phi \rangle}$ 이다. 

4. 따라서 $(c_1 |\psi_1\rangle + c_2|\psi_2)^\dagger = \overline{c_1}\langle \psi_1| + \overline{c_2}\langle \psi_2| = \langle \psi_1| \overline{c_1} +\langle \psi_1| \overline{c}_2$ 이다. 이로부터 다음이 성립한다.  
$$
\begin{aligned}
\langle \psi | \left(c_1  |\phi_1\rangle + c_2 | \phi_2\rangle\right) &= c_1 \langle \psi|\phi_1\rangle + c_2 \langle \psi|\phi_2\rangle, \\
(c_1 |\psi_1\rangle + c_2 |\psi_2\rangle)^\dagger| \phi \rangle & = \overline{c_1}\langle \psi_1|\phi \rangle + \overline{c_2}\langle\psi_2 |\phi\rangle. 
\end{aligned}
$$


6. $\langle \psi | A |\phi \rangle = \langle \psi| (A| \phi \rangle)$ 을 의미한다. 즉 브라켓 사이의 선형연산자는 켓에 대한 선형연산자를 의미한다. 또한 $(A|\psi\rangle)^\dagger |\phi\rangle = \langle \psi|A^\dagger|\phi\rangle$ 이다. 

:::


<br>

양자역학에서 캣은 양자상태를 표현하는 벡터이며 $0$ 이 아닌 $c\in \mathbb{F}$ 에 대해 $c|\psi \rangle$ 과 $|\psi\rangle$ 을 동일하다고 간주한다. 일반적으로 ket 은 $\langle \phi | \phi \rangle =1$ 인 정규화된벡터를 의미하는 경우가 많다. 또한 유한차원 복소벡터공간에서 양자상태를 표현한다면 $|\phi\rangle$ 을 열벡터로, $\langle \psi |$ 를 행벡터로 표현한다. 브라켓 표기법을 사용하는 이유를 요약하면 다음과 같다.

1. 양자 상태 표현의 편의성 : 브라켓으로 벡터를 표현할 때의 가장 큰 장점은 양자상태를 표현할 때 수학적인 표기법보다 편하다는 것이다. 예를 들어 양자수 3개로 정의되는 상태에 대해 $|abc\rangle$ 과 같이 세개의 숫자를 쓴 다음에 캣으로 묶어버리는 것으로 양자상태를 표현할 수 있다. 수소원자의 경우 주양자수 $n=2$, 궤도양자수 $l=1$, 자기양자수 $m=0$ 인 상태를 $|nlm\rangle$ 표기법을 사용하여 $|210\rangle$ 으로 표기할 수있다. 또한 내적에서 사용되는 쌍대기저를 독립적인 브라 표기법으로 $\langle 210 |$ 와 같이 표현 할 수 있다. 만약 브라켓 표기법 없이 사용한다면 $|210\rangle$ 상태를 $\Psi_{210}$ 이나 $\Phi^2_{10}$ 과 같이 표현해야 할 것이다. 

2. 연산자와 벡터의 분리 : $\langle\phi | \hat{A} |\psi\rangle$ 형식이기 때문에 연산자의 연산을 브라와 캣 사이의 공간에서 수행 할 수 있는데 이는 수식표기가 좀 더 깔끔해진다.

3. 연산자인 $|\phi\rangle\langle \psi|$ 와 내적인 $\langle \psi|\phi\rangle$ 의 구분이 명확해진다. 벡터를 사용한다면 $\boldsymbol{\psi} \boldsymbol{\phi}^\dagger$ 와 $\boldsymbol{\psi}^\dagger\boldsymbol{\phi}$ 와 같이 구분하기 힘들다. 

</br>

## 힐베르트 공간의 선형대수학

힐베르트 공간은 복소내적벡터공간이다. 즉 여기서는 복소내적벡터공간의 선형대수학을 다룬다.

</br>

### 영벡터 표기

원래 벡터공간은 영벡터를 항상 포함하며 수학에서는 $0$, $\boldsymbol{0}$ 혹은 $\overrightarrow{0}$ 과 같이 표기하며 벡터의 덧셈에 대한 항등원이다. 그러나 브라켓 표기법으로 $|0\rangle$ 은 어떤 $0$ 인 양자상태나 인덱스를 표기하는데 사용 될 수 있으며 이를 섞어 사용하는 것은 혼란을 준다. 따라서 여기서는 $|\varnothing\rangle$ 로 영벡터를 표현하기로 하자. 

</br>

### 기저와 차원

#### **선형독립**

벡터의 집합 $\{|1\rangle,\, |2\rangle,\ldots,\}$ 과 영벡터 $|\varnothing\rangle$ 에 대해 

$$
|\varnothing \rangle = c_1|1\rangle + c_2|2\rangle + \cdots \iff c_1=c_2=\cdots = 0
$$

일 때 $\{|1\rangle,\, |2\rangle,\ldots,\}$ 를 선형독립이라고 한다. 

</br>

#### **기저와 차원**

$\mathscr{H}$ 의 선형독립인 벡터의 집합 $\mathcal{B}=\{|\phi_1\rangle,\, |\phi_2\rangle,\ldots\}$ 의 선형결합으로 모든 벡터를 표현 할 수 있을 때 $\mathcal{B}$ 를 $\mathscr{H}$ 의 **기저(basis)** 라고 하고 기저에 속한 벡터를 **기저벡터(basis vector)** 라고 한다. 유한개의 기저벡터로 이루어진 기저가 존재한다면 $\mathscr{H}$ 를 유한차원 벡터공간이라고 하며 그렇지 않다면 무한차원 벡터공간이라고 한다. $\{|\phi_1\rangle, \ldots\}$ 가 기저일 때 

$$
|\phi\rangle = \sum_{j} c_j |\phi_j\rangle
$$

로 표현 할 수 있으며, 이 때 $c_j$ 는 유일하게 정해진다. 

벡터공간의 기저는 무한개가 가능하지만 유한차원 벡터공간일 경우 기저를 이루는 기저벡터의 수는 항상 같다. 이 기저벡터의 수를 벡터공간의 **차원(dimension)** 이라고 한다. 

</br>

#### **정규직교기저**
벡터 $|\phi\rangle$ 의 **크기 (norm)** 은 $\sqrt{\langle \phi|\phi\rangle}$ 로 정의된다. 벡터의 크기가 $1$ 인 벡터를 **단위벡터 (unit vector)** 라고 한다. 두 벡터의 내적이 $0$ 이면 두 벡터는 **직교한다(be orthogonal)** 라고 한다. 한 벡터가 다른 벡터의 스칼라배일 때 두 벡터는 **평행하다(be parallel)** 라고 한다. 벡터 $|\phi\rangle$ 에 대해

$$
|\phi'\rangle = \dfrac{|\phi\rangle}{\sqrt{\langle \phi|\phi\rangle}}
$$

은 단위벡터이다. 즉 임의의 벡터와 평행한 단위벡터를 항상 구할 수 있다.

기저 $\mathcal{B}$ 가 서로 직교하는 단위벡터로 이루어 져 있을 때 이 기저를 **정규직교기저(orthonormal basis)** 라고 한다. 기저가 있을 경우 항상 정규직교기저를 구할 수 있으며, 기저에 대해 정규직교기저를 구하는 방법중에 대표적인 것이 그람-슈미트 방법(Gram-Schmide method) 이다.  


</br>

### 벡터와 연산자의 행렬 표현

#### **벡터의 행렬표현**

$\mathscr{H}$ 에 대한 한 기저 $\mathcal{B}=\{|1\rangle,\, |2\rangle ,\ldots, |n\rangle \}$ 를 생각하자. 모든 벡터는 기저벡터의 선형결합으로 표현 할 수 있다.

$$
|\phi\rangle = \sum_{j}c_j |j\rangle.
$$

이 때 임의의 벡터 $|\phi\rangle$ 을 $\mathcal{B}$ 에 대해 열벡터로 아래와 같이 표현 할 수 있다. 즉 $n$ 차원 공간의 벡터는 $n \times 1$ 행렬로 표현할 수 있다. 

$$
[|\phi\rangle]_\mathcal{B} := \begin{bmatrix} c_1 \\ \vdots \\ c_n \end{bmatrix}
$$

를 벡터 $|\phi\rangle$ 의 기저 $\mathcal{B}$ 에 대한 행렬 표현이라고 한다.

</br>

#### **연산자와 행렬표현**

힐베르트 공간 $\mathscr{H}$ 에서 정의된 선형사상 $A:\mathscr{H} \to \mathscr{H}$ 를 **연산자(operator)** 라고 한다. 선형사상은 임의의 $|a\rangle,\, |b\rangle \in \mathscr{H},\, c\in \mathbb{F}$ 에 대해

$$
A(|a\rangle + c|b\rangle) =  A|a\rangle + c(A|b\rangle)
$$

인 함수를 의미한다. 

기저 $\mathcal{B}=\{|1\rangle,\, |2\rangle ,\ldots, |n\rangle \}$ 에 대해 $|\phi\rangle = \sum_{j}c_j |j\rangle$ 라고 하자. 그리고 $A|j\rangle = \sum_{i} A_{ij}|i\rangle$ 이라고 하자. 

$$
A|\phi\rangle = \sum_j c_j A|j\rangle = \sum_j\sum_i c_j A_{ij}|i\rangle
$$

이므로

$$
\left[A|\phi\rangle\right]_{\mathcal{B}} = \begin{bmatrix} \sum_j A_{1j}c_j\\ \vdots \\ \sum_j A_{nj}c_j\end{bmatrix} 
$$

이다. 연산자 $A$ 의 기저 $\mathcal{B} = \{|1\rangle,\, |2\rangle,\ldots,\,|n\rangle\}$ 에 대한 행렬 표현 $[A]_{\mathcal{B}}$ 를 다음과 같이 정의하자.

$$
[A]_{\mathcal{B}} = \begin{bmatrix} A_{11} & \cdots & A_{1n} \\ \vdots & \ddots & \vdots \\ A_{n1} & \cdots & A_{nn}\end{bmatrix}
$$

그렇다면

$$
[A|\phi\rangle]_{\mathcal{B}} = \begin{bmatrix} \sum_j A_{1j}c_j\\ \vdots \\ \sum_j A_{nj}c_j\end{bmatrix} = [A]_{\mathcal{B}}[|\phi\rangle]_{\mathcal{B}}
$$

임을 알 수 있다. 즉 정해진 기저 $\mathcal{B}$ 에 대해 벡터 뿐만 아니라 선형연산자도 행렬로 표현 할 수 있다. 지금까지 기저가 정규직교기저라는 가정을 하지 않았음에 유의하라. 여기가지는 임의의 기저에 대해 성립한다.

이제 정규직교기저를 생각해보자. 즉 $\mathcal{B} = \{|1\rangle,\, |2\rangle,\ldots,\,|n\rangle\}$ 가 정규직교 기저라면,

$$
\boxed{
\langle j|A|i\rangle = \sum_kA_{ik}\langle j| k\rangle = A_{ij}}
$$

임을 알 수 있다. 또한 $|\phi\rangle =\sum_i c_i|i\rangle,\, |\psi\rangle = \sum_j d_j|j\rangle$ 일 때

$$
\langle \psi|A|\phi\rangle = \sum_{i, j} \overline{d_j} c_i\langle j|A|i\rangle = \sum_{i, j} \overline{d_j} A_{ij} c_i = \left([|\psi\rangle]_{\mathcal{B}}\right)^\dagger [A]_{\mathcal{B}} [|\phi\rangle]_{\mathcal{B}}
$$

임을 알 수 있다. 

벡터와 연산자를 특정 기저에 대해 행렬로 표현 할 수 있으며, 이 때 각각 1-1 대응 관계가 존재한다. 이것을 선형대수학의 기본정리라고 부르기도 한다. 이제 연산자는 행렬로, 벡터는 열행렬로 표현 할 수 있다. 

</br>

### 닮음변환과 유니타리 변환

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CHM_similarity_transform}
#### 닮음 변환

어떤 행렬 $A$ 와 가역행렬 $S$ 에 대해 $SAS^{-1}$ 을 행렬 $A$ 에 대한 **닮은 변환(similarity transform)** 이라고 한다. $A$ 의 닮음변환으로 표현할 수 있는 행렬 $B$ 에 대해 $A$ 와 $B$ 는 서로 **닮았다 (be similar)** 라고 한다.

:::
:::

</br>

닮음 변환이 중요한 이유는 닮음 변환이 기저의 변환이기 때문이다. 기저 $\mathcal{B}=\{|i\rangle : i=1,\,2,\ldots\}$ 를 생각하자. 가역행렬, 즉 가역 선형 연산자 $S$ 에 대해 $S\mathcal{B} = \{S|i\rangle :i=1,\ldots\}$ 가 선형 독립임을 보이자. 

$$
|\varnothing\rangle = \sum_{i=1} c_i S|i\rangle = S\left( \sum_{i=1} c_i |i\rangle\right)
$$

$S$ 가 가역이므로 $\left( \sum_{i=1} c_i |i\rangle\right)=|\varnothing\rangle$ 이며 따라서 모든 $c_i=0$ 이다. 따라서 $S\mathcal{B}$ 역시 기저이다. 



::: {.callout-note appearance="simple" icon="false"}
::: {#def-CHM_unitary_transform}
#### Hermite conjugate 와 유니타리 연산자

연산자 $A$ 에 대해 $(A|\psi)^\dagger |\phi\rangle = \langle \psi |A^\dagger |\phi\rangle$ 을 만족하는 $A^\dagger$ 는 항상 존재하며 역시 $\mathscr{H}$ 에서의 선형연산자이다. $A$ 에 대해 $A^\dagger$ 를 $A$ 에 대한 **Hermitian cojugate** 혹은 **Hermitian adjoint** 라고 한다. $U^{-1}=U^\dagger$ 인 연산자를 **유니타리 연산자 (unitary operator)** 라고 한다. 참고로 실벡터 공간에서 정의된, 즉 모든 성분이 실수인 행렬일 경우 $U^\dagger = ^T$ 이다. 어떤 행렬 $O$ 가 $O^{-1}=O^T$ 일 때 **직교 연산자 (orthogonal operator)** 라고 한다. 

:::
:::

</br>


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_hermitian_conjugate}

#### Hermitian conjugate 
연산자 $L$ 과 $L^\dagger$ 을 생각하자.

$$
\langle \psi|L^\dagger|\phi\rangle = \left(L|\psi\right)^\dagger |\phi\rangle = \overline{|\phi\rangle^\dagger \left(L|\psi\rangle\right)} = \overline{\langle \phi | L|\psi\rangle}
$$

즉 다음이 성립한다. 

$$
\boxed{
\langle \psi|L^\dagger|\phi\rangle  = \overline{\langle \phi | L|\psi\rangle}}
$$ {#eq-CHM_hermitan_conjugate}

:::

</div>
</br>

우선 유니타리 행렬은 정의상 가역행렬이므로 유니타리 행렬에 의한 닮음 변환이 가능하다. 이를 연산자의 **유니타리 변환 (Unitary transform)** 이라고 한다. 즉 연산자 $L$ 과 유니타리 연산자 $U$ 에 대해 $ULU^{-1}$ 는 연산자의 유니타리 변환이다. 벡터 $|\phi\rangle$ 에 대해 $U|\phi\rangle$ 은 벡터의 유니타리 변환이다. 벡터의 유니타리 변환의 경우 다음이 성립한다.
$$
\langle U\phi |U\psi\rangle = \langle \phi| U^\dagger U|\psi\rangle = \langle \phi|\psi\rangle
$$  

즉 유니타리 연산자에 의해 변환된 두 벡터의 내적은 변하지 않는다. 따라서 정규직교기저를 유니타리 행렬로 변환시키더라도 정규직교기저가 된다. 

</br>

### 고유값과 고유벡터

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CHM_eigenvector}
#### 고유값과 과유벡터

영벡터가 아닌 벡터 $|\phi\rangle$ 과 연산자 $\Lambda$ 에 대해

$$
\Lambda |\phi\rangle = \lambda|\phi\rangle
$$

을 만족하는 스칼라 $\lambda$ 가 존재할 때 $|\phi\rangle$ 을 연산자 $\Lambda$ 에 대해 $\lambda$ 의 **고유값 (eigenvalue)** 을 갖는 **고유벡터 (eigenvector)** 라고 한다. 

:::
:::


$|\phi\rangle$ 과 $|\psi\rangle$ 이 연산자 $\Lambda$ 에 대해 같은 고유값 $\lambda$ 를 갖는다면 $|\phi\rangle$ 과 $|\psi\rangle$ 의 임의의 선형 결합 역시 고유값 $\lambda$ 를 갖는 고유벡터임을 보일 수 있다.

$$
\Lambda (a|\phi\rangle + b|\psi\rangle) = a\Lambda|\phi\rangle + b\Lambda|\psi\rangle = \lambda(a|\phi\rangle + b|\psi\rangle).
$$

따라서 $\Lambda$ 에 대해 같은 고유값을 갖는 벡터의 집합과 $|\varnothing\rangle$ 의 합집합은 $\mathscr{H}$ 의 부분공간을 이루며 이를 $\Lambda$ 에 대한 **고유공간(eigenspace)** 이라고 한다. 서로 선형독립인 두 벡터가 같은 고유값을 가질 때 이 두 벡터는 **축퇴되었다 (be degenerated)** 고 표현한다.

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_similar_transform_and_eigenvector}

연산자 $L$ 에 대한 고유값은 유니타리 변환에 대해 불변이다. 

::: 
</div>

</br>

::: {.proof}

$L|\phi\rangle = \lambda |\phi\rangle$ 이라고 하자. 유니타리 연산자 $U$ 에 의한 유니타리 변환 $L'=ULU^\dagger,\, U|\phi\rangle$ 을 생각하자.

$$
(ULU^\dagger)(U|\phi\rangle) = UL|\phi\rangle = \lambda (U|\phi\rangle)
$$

이므로 $U|\phi\rangle$ 이 고유값 $\lambda$ 를 갖는 $ULU^\dagger$ 의 고유벡터이다. $\square$

:::

</br>



<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_orthogonality_of_eigen_vectors_with_different_eigenvalues}

서로 다른 고유값을 갖는 두 벡터는 선형 독립이다.

::: 
</div>

</br>

::: {.proof}

연산자 $L$ 의 두 고유벡터 $|1\rangle,\, |2\rangle$ 이 각각 $l_1,\,l_2$ 서로 다른 고유값을 가진다고 하자.

$$
|\varnothing \rangle = a_1|1\rangle + a_2|2\rangle
$$

라고 놓자. 

$$
L|\varnothing \rangle = |\varnothing\rangle = a_1L|1\rangle + a_2L|\rangle = a_1l_1|1\rangle +a_2l_2|2\rangle = (l_2-l_1)a_2|2\rangle
$$

이다. $l_1\ne l_2$ 이므로 $a_2=0$ 이며, 따라서 $a_1=0$ 이다. 즉 두 벡터는 선형 독립이다. $\square$

:::

</br>


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_different_eigenvalue_non_orthogonal}

#### 서로 다른 고유값을 갖지만 직교하지 경우

</br>

$A=\begin{bmatrix} 2 & 1 \\ 0 & 3\end{bmatrix}$ 에 대해 $v_1 =\begin{bmatrix} 1 \\ 0\end{bmatrix}$ 와 $v_2 = \begin{bmatrix}1 \\ 1\end{bmatrix}$ 는 각각 $2$ 와 $3$ 을 고유값으로 갖는 고유벡터지만 $v_1^Tv_2=1$ 로 직교하지 않는다.  

:::

</div>

</br>


### 행렬의 대각화


::: {.callout-note appearance="simple" icon="false"}
::: {#def-CHM_diagonalization}
#### 행렬의 대각화

정사각행렬이 어떤 닮음 변환에 의해 대각행렬로 변화할 때 행렬이 **대각화되었다(be diagonalized)** 고 하고, 이런 행렬을 **대각화 가능 행렬(daignalizable matrix)** 이라고 한다.


:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CHM_diagonalizatoin_of_matrix}

정사각행렬 $A$ 에 대해 다음 두 명제는 동치이다.

&emsp;($a$) $A$ 는 대각화 가능하다.

&emsp;($b$) $A$ 의 고유벡터로 이루어진 기저가 존재한다.

:::

</div>
</br>

::: {.proof}

($a\implies b$) 어떤 가역행렬 $S$ 에 대해 $M=S^{-1}AS$ 이 대각행렬이라고 하고 $m_i = M_{ii}$ 라고 하자. 대각 행렬에 대해 표준기저벡터 $|e_i\rangle,\, i=1,\,2,\ldots$ 는 $m_i$ 를 고유값으로 갖는 고유벡터이며 

$$
A(S|e_i\rangle) = SS^{-1}AS|e_i\rangle = SM|e_i\rangle= m_i(S|e_i\rangle)
$$

이다. 즉 $S|e_i\rangle$ 은 $A$ 의 고유벡터이며, 기저이다.

($b\implies a$) $\{|x_i\rangle:\,i=1,\ldots\}$ 의 각각의 벡터가 $\lambda_i$ 를 고유값으로 갖는 기저라고 하자. $L|i\rangle = \lambda_i|i\rangle$ 이므로 이 기저에서의 행렬표현은 대각행렬이다. $\square$


:::

</br>

이제 연산자의 고유값과 고유벡터에 대해 다시 생각해보자. 연산자 $L$ 에 대해 고유값 $\lambda$ 를 가진 벡터 $|l\rangle$ 이 존재한다면 $L|l\rangle = \lambda |l\rangle$ 이므로 $(L-\lambda I)|l\rangle = |\varnothing\rangle$ 이다. 즉 $L-\lambda I$ 는 가역행렬이 아니며 따라서 $\det(L-\lambda I) = 0$ 이다. 
유한차원 벡터공간이라면 $\det(L-\lambda I)$ 는 $\lambda$ 에 대한 다항식으로 **특성 다항식 (characteristic polynomial)** 라고 불리며 같은 이유로 $\det(L-\lambda I)=0$ 을 **특성 다항식 (characteristic equation)** 이라고 부른다. 

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_eigenvalue_and_roots_of_polynomial}

유한차원 $\F$-벡터공간 $V$ 에서 정의된 연산지 $L$ 에 대해 두 명제는 동치이다.

&emsp;($a$) $\lambda\in \F$ 는 $L$ 의 고유값이다.

&emsp;($b$) $\det (L-\lambda I)=0$ 이다.

:::

</div>
</br>

::: {.proof}

($a \implies b$) 는 위에서 보였다.

($b \implies a$) $(L-\lambda I)|\phi\rangle = |\varnothing\rangle$ 인 $|\phi\rangle \in V$ 가 존재한다. $\square$

:::

</br>

$n$-차원 벡터공간에서 $\det(L-\lambda I)$ 는 $n$ 차 다항식임을 안다. 만약 $\F= \C$ 라면 대수학의 기본정리에 의해 $\det(L-\lambda I)=0$ 을 만족하는 최소한 하나의 $\lambda$ 가 존재한다. 즉 우리는 다음을 알 수 있다.


</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_existance_of_eigenvalue_in_complex_vector_space}

유한차원 복소벡터공간에서는 최소한 하나의 고유벡터가 존재한다.

:::

</div>
</br>


</br>

### 에르미트 연산자

::: {.callout-note appearance="simple" icon="false"}
::: {#def-CHM_heritian}
#### 에르미트 연산자
연산자 $A$ 가 $A^\dagger = A$ 일 때 이 연산자를 **에르미트 연산자 (Heritiaan operator)** 라고 한다. 

:::
:::

</br>

양자역학에서 에르미트 연산자는 매우 중요하며 특별히 다룰 가치가 있다. 

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CHM_basic_properties_of_hermitian_operator}

#### 에르미트 연산자의 기본적인 성질

복소벡터 벡터공간 $V$ 에서의 에르미트 연산자에 대해 다음이 성립한다.

&emsp;($1$) $\left(A^\dagger\right)^\dagger = A$ 이다. 

&emsp;($2$) 에르미트 연산자의 고유값은 실수이다.

&emsp;($3$) 서로 다른 고유값을 갖는 에르미트 연산자의 고유벡터는 직교한다.

:::

</div>

</br>

::: {.proof}

($1$) $\langle \phi|\left(A^\dagger\right)^\dagger|\psi\rangle = \overline{\langle \psi |A^\dagger |\phi\rangle} = \overline{\overline{\langle \phi |A|\psi\rangle}}=\langle \phi |A|\psi\rangle$. 

($2$) 에르미트 연산자 $A$ 에 대해 $|a\rangle$ 이 고유값 $a$ 를 갖는 고유벡터라고 하자. 즉 $A|a\rangle = a|a\rangle$ 이다. 

$$
\overline{a}=\overline{\langle a|A|a\rangle} = \langle a|A^\dagger |a\rangle = \langle a|A|a\rangle = a
$$

($3$) $|a\rangle,\, |b\rangle$ 이 각각 $a,\,b\in \R$ 를 고유값으로 갖는 에르미트 연산자 $L$ 의 고유벡터이며 $a\ne b$ 라고 하자. 

$$
\begin{aligned}
0 = \langle a|(L-L)|b\rangle = \langle a|L|b\rangle - \langle a|L|b\rangle = (L|a\rangle)^\dagger |b\rangle - \langle a\left(L|b\rangle \right) = (a-b)\langle a|b\rangle
\end{aligned}
$$

이다. $a\ne b$ 이므로 $\langle a|b\rangle  = 0$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CHM_diagonalizatoin_of_hermitian_operator}

#### 에르미트 행렬의 대각화

</br> 

유한차원 복소벡터공간에서 다음이 성립한다.

&emsp;($1$) 에르미트 연산자에 대한 교유벡터로 벡터공간의 정규직교기저를 구성 할 수 있다.

&emsp;($5$) 에르미트 연산자는 특정 기저에 대해 대각행렬로 표현 될 수 있다.

::: 
</div>

</br>

::: {.proof}

($1$) $A$ 가 $n$ 차원 벡터공간에서의 에르미트 연산자라고 하고 Induction 을 이용하여 증명한다. 우선 1차원에서는 자명하다. 이제 $1$ 차원 부터 $n-1$ 차원까지 성립한다고 가정하자. @prp-CHM_existance_of_eigenvalue_in_complex_vector_space 에 의해 하나의 고유벡터 $|\phi\rangle$ 이 존재한다. 이때의 고유값을 $\lambda$ 라고 하자. 그렇다면 $\lambda$ 의 고유값을 가진 벡터의 집합이 $n$ 차원이라면, 즉 모든 벡터가 $\lambda$ 의 고유값을 갖는 고유벡터라면 정규직교 기저에 의해 연산자는 대각화된다. $\lambda$ 의 고유값을 가진 벡터의 집합이 $n$ 차원 보다 작다면 $\lambda$ 의 고유값을 가진 부분공간과 $\lambda$ 이외의 고유값을 가진 부분공간으로 분해된다. 각각의 부분공간이 $n$ 보다 작은 차원이므로 가정에 의해 각각 정규직교기저를 구성 할 수 있으며, 이 정규직교기저의 합집합이 전체 벡터공간의 정규직교 기저가 된다. 

($2$) ($1$) 과 @thm-CHM_diagonalizatoin_of_matrix 에 의해 성립한다. $\square$

:::

</br>

### Compatible operators {#sec-CHM_compatible_operators}

::: {.callout-note appearance="minimal"}

::: {#def-CHM_commutator_of_operators}

#### Commutator 

두 연산자 $L,\,M$ 에 대해 

$$
[L,\,M] := LM-ML
$$ {#eq-CHM_commutators}

을 두 연산자에 대한 **commutator** 라고 한다. $[L,\,M]=0$ 이면 두 연산자는 **compatible** 하다고 한다.

:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_uncertainty_1}

힐베르트 공간 $\mathscr{H}$ 에서 정의된 두 에르미트 연산자 $L,\,M$ 에 대해 다음은 동치이다.

&emsp;($a$) $[L,\,M]= 0$.

&emsp;($b$) $L$ 과 $M$ 에 대해 동시에 모두 고유벡터인 벡터로 이루어진 $\mathscr{H}$ 의 기저가 존재한다.
:::

</div></br>

::: {.proof}

($a \implies b$) $L$ 과 $M$ 이 에르미트 연산자이므로 각각의 고유상태로 이루어진 $\mathscr{H}$ 의 기저가 존재한다. 고유값 $l_i$ 인 $L$ 의 고유상태를 $|l_i\rangle$ 로 표기하자. 

$$
|\varnothing\rangle=[L,\,M]|l_i\rangle = (LM- M l_i) |l_i\rangle = (L- l_i) M|l_i\rangle
$$

이므로 $M|l_i\rangle$ 는 고유값 $l_i$ 를 갖는 $L$ 의 고유상태이다. $M$ 역시 에르미트 연산자이므로 

$$
M|l_i\rangle = \sum_j m_j|l_i m_j\rangle
$$

로 쓸 수 있다. 따라서 $\mathscr{H}$ 는 $\{|l_i m_j\rangle \}$ 를 기저로 갖는다.

($b \implies a$) $L$ 과 $M$ 에 대해 각각 $l,\,m$ 의 고유값을 갖는 동시에 고유상태인 기저를 $|lm\rangle$ 라고 하면 

$$
[L,\,M]|lm\rangle = LM|lm\rangle - ML|lm\rangle = (lm-lm)|lm\rangle = |\varnothing\rangle
$$

이므로 $[L,\,M] = \hat{0}$ 이다. $\square$
:::

</br>

@prp-CHM_uncertainty_1 은 양자역학이 degeneracy 를 해결하는 방법을 말해준다. 어떤 에르미트 연산자 $L$ 에 대하나 고유상태가 degenrated 되어 있을 경우 $L$ 과 compatible 한 연산자 $M$ 을 찾으며, 운이 좋다면 $L$ 의 degenerated 된 고유공간를 $M$ 의 고유상태로 분해 할 수 있다. $L,\,M$ 이 compatible 하므로 이 분해된 고유공간 역시 $L$ 의 고유공간이므로 우리의 목적을 해치지 않는다. 만약 $L$ 에 대해 compatible 한 모든 연산자에 대해 분해되지 않는 2차원 이상의 고유공간이 존재한다면 이것은 자연이 우리에게 허용하지 않은 구분이다. 그러나 실제적인 경우에는 이런것은 존재하기 힘들다.(@Sakurai1994)


</br>

## 무한차원에 대해 {#sec-CHM_infinite_dimesion}

### 디랙 델타함수 {#sec-CHM_dirac_delta_function}

양자역학에서 위치 $x$ 나 운동량 $p$ 와 같은 연속적인 값을 다루는데는 디렉 댈타 함수 $\delta (x)$ 가 필수적이다.

::: {.callout-note appearance="minimal"}

::: {#def-CHM_dirac_delta_function}

#### 1차원 디랙 델타 함수

1차원 디렉 델타 함수 $\delta(x)$ 는 아래의 성질을 만족하는 함수이다.

&emsp; ($1$) $\delta (x) = \left\{ \begin{array}{ll} +\infty \qquad & ;\text{x=0}.\\ 0 &;\text{oterwise}.  \end{array}\right.$

&emsp; ($2$) $\displaystyle \int_{-\infty}^\infty f(x)\, \delta (x) \, dx = f(0)$.

:::

:::


여기서는 참고를 위해 디랙 델타함수의 성질에 대해 증명 없이 기술하기로 한다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CHM_properties_of_dirac_delta_function}

#### 디랙 델타 함수의 성질

디랙 델타 함수 $\delta(x)$ 는 아래의 성질을 만족한다.

&emsp; ($1$) $\delta (-x) = \delta (x)$,

&emsp; ($2$) $\displaystyle \int f(x) \delta (x-x')\, dx = f(x')$,

&emsp; ($3$) $\delta (ax) = \dfrac{1}{|a|}\delta (x)$,

&emsp; ($4$) $g(x)=0$ 의 해 $\{x_i\}$ 에 대해 모든 $x_i$ 에서 $g(x_i)\ne 0$ 일 때 $\displaystyle \delta (g(x)) = \sum_{i} \dfrac{\delta(x-x_i)}{|g'(x_i)|}$,

&emsp; ($5$) $\displaystyle \int f(x)\, \delta'(x)\, dx = f'(0)$, 

&emsp; ($6$) $x\,\delta'(x) = - \delta(x)$

&emsp; ($7$) $\displaystyle \dfrac{1}{2\pi}\int_{-\infty}^\infty e^{ikx}\, dk = \delta (x)$. 

:::

</div></br>

### 무한차원 벡터공간에서의 연속적인 변수에 대한 기술

$$
\sum_i |a_i\rangle \langle a_i|\psi\rangle \longrightarrow \int | x\rangle \langle  x|\psi\rangle \, dx
$$

$$
\langle x|x'\rangle = \delta(x-x')
$$

</br>

### 연습문제 {.unnumbered}


</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-sakurai_1_4}

#### Sakurai 1.4

브라켓 표기법에서 아래 명제를 증명하거나 계산하라.

($1$) 연산자 $X,\,Y$ 에 대해 $\tr (XY) = \tr(YX)$ 이다.

($2$) 연산자 $X,\,Y$ 에 대해 $(XY)^\dagger = Y^\dagger X^\dagger$ 이다.

($3$) 에르미트 연산자 $A$ 에 대해 고유값들을 모두 알고 있을 때 $\exp [if(A)]$ 를 브라켓 형태로 표현하라.

($4$) $\psi_{a'}(\bf{x}') = \langle \bf{x}|a'\rangle$ 일 때 $\sum_{a'} \psi^\ast_{a'}(\bf{x}') \psi_{a'}(\bf{x}'')$ 를 구하라.

:::

</div></br>

::: {.solution}

($1$) 임의의 기저 $\{|i\rangle\}$ 에 대해

$$
\tr (XY)= \sum_i \sum_j\langle i|X|j\rangle \langle j|Y|i\rangle =  \sum_j \sum_i\langle j|Y|i\rangle \langle i|X|j\rangle = \tr (YX).
$$

($2$) $\langle i|(XY)^\dagger|j\rangle = \langle XYi|j\rangle = \langle Yi|X^\dagger|j\rangle = \langle i|Y^\dagger X^\dagger|j\rangle$.

($3$) $A$ 의 고유값 $a$ 에 대한 고유벡터 $|a\rangle$ 가 힐베르트 공간의 정규직교기저를 이룬다고 하자. 

$$
e^{if(A)} = \sum_{a} e^{if(A)}|a\rangle \langle a| = \sum_a e^{if(a)}|a\rangle \langle a|
$$


($4$) $\sum_{a'}\psi^\ast_{a'}(\bf{x}')\psi_{a'}(\bf{x}'')=\sum_{a'}\langle a'|\bf{x'}\rangle \langle \bf{x}'' |a'\rangle = \sum_{a'}\langle \bf{x}''|a'\rangle \langle a'|\bf{x}'\rangle = \delta(\bf{x}'-\bf{x}'')$

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-sakurai_1_5}

#### Sakurai 1.5

($a$) 두 캣 $|\alpha\rangle,\, |\beta\rangle$ 을 생각하자. $|a'\rangle,\, |a''\rangle,\ldots$ 가 힐베르트 공간에서의 정규직교를 이루며 $\langle a'|\alpha\rangle,\, \langle a''|\alpha\rangle, \ldots$ 와 $\langle a'|\beta\rangle,\, \langle a''|\beta\rangle, \ldots$ 를 알고 있다고 하자. $|\alpha\rangle\langle \beta|$ 의 행렬 표현을 구하라.

($b$) 스핀 $\frac{1}{2}$ 시스템을 생각하자. $|\alpha\rangle$ 과 $|\beta\rangle$ 이 각각 $|s_z=\hbar/2\rangle$ 과 $|s_x=\hbar/2\rangle$ 이라고 하자. $|\alpha\rangle \langle \beta|$ 를 $S_z$ 직교 기저에서의 행렬로 표현하라.

:::

</div></br>

::: {.solution}

($a$) $\langle a'|\alpha\rangle \langle \beta|a''\rangle$. 

($b$) $|+\rangle,\, |-\rangle$ 을 $s_z$ 기저에서의 각각 $+\hbar/2,\, -\hbar/2$ 에 대한 고유벡터라고 하자. $\beta\rangle = \dfrac{1}{\sqrt{2}}(|+\rangle + |-\rangle)$ 이므로

$$
|\alpha\rangle\langle \beta| = 
$$


:::