---
title: "Part2-1"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

```{r, engine = 'tikz'}
#| label: fig-part2_double_slit_wave
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "파동의 이중슬릿"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw (-4, -2) -- (-4, 2);
\draw (-3.7, -2) -- (-3.7, 2);
\draw (-3.4, -2) -- (-3.4, 2);
\draw (-3.1, -2) -- (-3.1, 2);
\draw (-2.8, -2) -- (-2.8, 2);

\draw[-{Stealth[length=1.5mm]}] (-3.4, -2.3) node [left] {$k$} -- (-3.0, -2.3);

\draw[very thick] (0, 3) -- (0, 0.55) node [above left] {$S_1$};
\draw[very thick] (0, 0.45) -- (0, -0.45); 
\draw[very thick]  (0, -3) -- (0, -0.55) node [below left] {$S_2$};

\draw [dashed] (0, 0.8) arc (90:-90:0.3);
\draw [dashed] (0, 1.0) arc (90:-90:0.5);
\draw [dashed] (0, 1.2) arc (90:-90:0.7);

\draw [dashed] (0, -0.8) arc (-90:90:0.3);
\draw [dashed] (0, -1.0) arc (-90:90:0.5);
\draw [dashed] (0, -1.2) arc (-90:90:0.7);


\draw (0, -3.2) -- (0, -3.6);
\draw (4, -3.2) -- (4, -3.6);
\draw [blue, {Stealth[length=1.5mm]}-{Stealth[length=1.5mm]}] (0.0, - 3.4) -- (4.0, -3.4);
\node [below] at (2, -3.4) {$d$};

\draw (-0.5, 0.5) -- (-0.1, 0.5);
\draw (-0.5, -0.5) -- (-0.1, -0.5);
\draw [teal, {Stealth[length=1.5mm]}-{Stealth[length=1.5mm]}] (-0.3, 0.5) -- (-0.3, -0.5);
\node [left] at (-0.3, 0.0) {$a$};

\draw[very thick, red] (4, 3) -- (4, -3);

\draw[red, dashed, thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({-exp(-(\t-0.5)^2/4)+4},{\t});
\node[left, red] at (3.5, 2.3) {$I_1$};
\draw[teal, dashed, thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({-exp(-(\t+0.5)^2/4)+4},{\t});
\node[left, teal] at (3.5, -2.3) {$I_2$};

\draw[blue, dashed, very thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({2*exp(-(\t)^2/1) * (cos (\t*250))^2 +4.5 },{\t});
\draw [-{Stealth[length=1.5mm]}] (4.5, 3) -- (4.5, -3) node [below] {$x$};
\node[right, blue] at (6.5, 0) {$I_{1+2}\ne I_1+I_2$};


\draw[-{Stealth[length=1.5mm]}] (0.0, 0.5) -- (4.0, 1.0);
\draw[-{Stealth[length=1.5mm]}] (0.0, -0.5) -- (4.0, 1.0);

\node [above] at (2.0, 0.75) {$d_1$};
\node [below] at (2.0, 0.25) {$d_2$};
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_double_slit_particle
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "입자의 이중슬릿"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[very thick] (-4, -0.3) -- (-3, -0.3) -- (-3, 0.3) -- (-4, 0.3);
\node [below left] at (-3, -0.3) {$S$};

\draw[dashed, -{Stealth[length=1.5mm]}] (-2.7, 0.2) -- (-1, 0.6);
\draw[dashed, -{Stealth[length=1.5mm]}] (-2.7, 0.1) -- (-1, 0.25);
\draw[dashed, -{Stealth[length=1.5mm]}] (-2.7, -0.1) -- (-1, -0.25);
\draw[dashed, -{Stealth[length=1.5mm]}] (-2.7, -0.2) -- (-1, -0.6);

\draw[very thick] (0, 3) -- (0, 0.55) node [above right] {$S_1$};
\draw[very thick] (0, 0.45) -- (0, -0.45); 
\draw[very thick]  (0, -3) -- (0, -0.55) node [below right] {$S_2$};

\draw (0, -3.2) -- (0, -3.6);
\draw (4, -3.2) -- (4, -3.6);
\draw [blue, {Stealth[length=1.5mm]}-{Stealth[length=1.5mm]}] (0.0, - 3.4) -- (4.0, -3.4);
\node [below] at (2, -3.4) {$d$};

\draw (-0.5, 0.5) -- (-0.1, 0.5);
\draw (-0.5, -0.5) -- (-0.1, -0.5);
\draw [teal, {Stealth[length=1.5mm]}-{Stealth[length=1.5mm]}] (-0.3, 0.5) -- (-0.3, -0.5);
\node [left] at (-0.3, 0.0) {$a$};

\draw[very thick, red] (4, 3) -- (4, -3);

\draw[red, dashed, thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({-exp(-(\t-0.5)^2/4)+4},{\t});
\node[left, red] at (3.5, 2.3) {$I_1$};
\draw[teal, dashed, thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({-exp(-(\t+0.5)^2/4)+4},{\t});
\node[left, teal] at (3.5, -2.3) {$I_2$};

\draw[blue, dashed, very thick] plot[variable=\t,domain=-3:3, samples=100, smooth,thick] ({exp(-(\t+0.5)^2/4) +exp(-(\t-0.5)^2/4) + 4.5 },{\t});
\draw [-{Stealth[length=1.5mm]}] (4.5, 3) -- (4.5, -3) node [below] {$x$};
\node[right, blue] at (6.5, 0) {$I_{1+2}=I_1+I_2$};

\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_infinite_potential_well_1
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 8
#| fig-align: center
#| fig-cap: "무한 포텐셜 우물"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[, -{Stealth[length=2mm]}] (0, 0) -- (0, 3) node [above] {$V(x)$};
\draw[, -{Stealth[length=2mm]}] (-3, 0) -- (3, 0) node [below left] {$x$};
\draw[red, thick, -{Stealth[length=2mm]}] (-2, 0) -- (-2, 3);
\draw[red, thick, -{Stealth[length=2mm]}] (2, 0) -- (2, 3);
\draw[red, thick] (-2, 0) -- (2, 0);
\node[below] at (-2, 0) {$-L/2$};
\node[below] at (2, 0) {$L/2$};

\fill [fill=red,fill opacity=0.3] (-2,0) rectangle (-3,3);
\node[] at (-2.5, 1) {$\rm{I}$};
\node[] at (-0.5, 1) {$\rm{II}$};
\node[] at (2.5, 1) {$\rm{III}$};

\fill [fill=red,fill opacity=0.3] (2,0) rectangle (3,3);

\begin{scope}[shift={(8,0)}]
\draw[, -{Stealth[length=2mm]}] (0, 0) -- (0, 3) node [above] {$V(x)$};
\draw[, -{Stealth[length=2mm]}] (-3, 0) -- (3, 0) node [below left] {$x$};
\draw[red, thick] (-2, 0) -- (-2, 3);
\draw[red, thick] (2, 0) -- (2, 3);
\draw[red, thick] (-2, 0) -- (2, 0);
\node[below] at (-2, 0) {$-L/2$};
\node[below] at (2, 0) {$L/2$};


\draw[teal, thick] plot[variable=\t,domain=-2:2, samples=100, smooth,thick] ({\t}, { 0.5*cos( \t * 45) + 0.5});
\draw[] (-2, 0.5) -- (2, 0.5) node [right] {$E_2$};
\node[above] at (1.0, 1.0) {$\psi_1$};


\draw[teal, thick] plot[variable=\t,domain=-2:2, samples=100, smooth,thick] ({\t}, { 0.5*sin( \t * 90) + 2});
\draw[] (-2, 2) -- (2, 2) node [right] {$E_1$};
\node[above] at (1.0, 2.5) {$\psi_2$};

\end{scope}
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_potential_well_1
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 3
#| fig-align: center
#| fig-cap: "포텐셜 우물"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[, -{Stealth[length=2mm]}] (0, 0) -- (0, 3) node [above] {$V(x)$};
\draw[, -{Stealth[length=2mm]}] (-3, 0) -- (3, 0) node [below left] {$x$};
\draw[red, thick, ] (-3, 2) -- (-2, 2) -- (-2, 0) -- (2, 0) -- (2, 2) -- (3, 2);
\node[below] at (-2, 0) {$-a$};
\node[below] at (2, 0) {$a$};

\fill [fill=red,fill opacity=0.3] (-2,0) rectangle (-3,2);
\fill [fill=red,fill opacity=0.3] (2,0) rectangle (3,2);

\node[] at (-2.5, 1) {$\rm{I}$};
\node[] at (-0.5, 1) {$\rm{II}$};
\node[] at (2.5, 1) {$\rm{III}$};

\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_solution_of_potential_well
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 9
#| fig-align: center
#| fig-cap: "무한 포텐셜 우물"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\node [] at (-0.7, 5.8) {$(a)$};
\draw[, -{Stealth[length=2mm]}] (0, -0.2) -- (0, 6) node [above] {$\kappa$} ;
\draw[, -{Stealth[length=2mm]}] (-0.2, 0) -- (5.5, 0) node [right] {$ka$};
\draw[teal, thick] plot[variable=\t, domain=0:0.9, samples=100, smooth,thick] ({\t}, {\t * tan( 90*\t)}) node [black, above right] {$ka \tan (ka)$};
\draw[teal, thick] plot[variable=\t, domain=2:2.71, samples=100, smooth,thick] ({\t}, {\t * tan( 90*\t)});
\draw[teal, thick] plot[variable=\t, domain=4:4.57, samples=100, smooth,thick] ({\t}, {\t * tan( 90*\t)}) ;

\draw[thick, dotted] (1, 6) -- (1, 0);
\node [scale=0.9] at (1, -0.2) {$\pi/2$};
\draw[thick, dotted] (2, 6) -- (2, 0);
\node [scale=0.9] at (2, -0.2) {$\pi$};
\draw[thick, dotted] (3, 6) -- (3, 0);
\node [scale=0.9] at (3, -0.2) {$3\pi/2$};
\draw[thick, dotted] (4, 6) -- (4, 0);
\node [scale=0.9] at (4, -0.2) {$2\pi$};
\draw[thick, dotted] (5, 6) -- (5, 0);
\node [scale=0.9] at (5, -0.2) {$5\pi/2$};

\draw[red, thick] (1.2, 0) arc (0:90:1.2) node [black, left] {$a\sqrt{2mV_0/\hbar^2 - k^2}$};
\draw[red, thick] (2.4, 0) arc (0:90:2.4);
\draw[red, thick] (3.6, 0) arc (0:90:3.6);
\draw[red, thick] (4.8, 0) arc (0:90:4.8);



\begin{scope}[shift={(8.5,0)}]
\node [] at (-0.7, 5.8) {$(b)$};
\draw[, -{Stealth[length=2mm]}] (0, -0.2) -- (0, 6) node [above] {$\kappa$} ;
\draw[, -{Stealth[length=2mm]}] (-0.2, 0) -- (6.2, 0) node [right] {$ka$};
\draw[teal, thick] plot[variable=\t, domain=1:1.81, samples=100, smooth,thick] ({\t}, {-\t * cot( 90*\t)}) node[black, above] {$-ka \cot (ka)$};
\draw[teal, thick] plot[variable=\t, domain=3:3.65, samples=100, smooth,thick] ({\t}, {-\t * cot( 90*\t)});
\draw[teal, thick] plot[variable=\t, domain=5:5.5, samples=100, smooth,thick] ({\t}, {-\t * cot( 90*\t)});

\draw[thick, dotted] (1, 6) -- (1, 0);
\node [scale=0.9] at (1, -0.2) {$\pi/2$};
\draw[thick, dotted] (2, 6) -- (2, 0);
\node [scale=0.9] at (2, -0.2) {$\pi$};
\draw[thick, dotted] (3, 6) -- (3, 0);
\node [scale=0.9] at (3, -0.2) {$3\pi/2$};
\draw[thick, dotted] (4, 6) -- (4, 0);
\node [scale=0.9] at (4, -0.2) {$2\pi$};
\draw[thick, dotted] (5, 6) -- (5, 0);
\node [scale=0.9] at (5, -0.2) {$5\pi/2$};
\draw[thick, dotted] (6, 6) -- (6, 0);
\node [scale=0.9] at (6, -0.2) {$3\pi$};

\draw[red, thick] (1.2, 0) arc (0:90:1.2) node[black, left] {$a\sqrt{2mV_0/\hbar^2-k^2}$};
\draw[red, thick] (2.4, 0) arc (0:90:2.4);
\draw[red, thick] (3.6, 0) arc (0:90:3.6);
\draw[red, thick] (4.8, 0) arc (0:90:4.8);
\end{scope}
\end{tikzpicture}
```

</br>


```{r, engine = 'tikz'}
#| label: fig-part2_step_potential
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 4
#| fig-align: center
#| fig-cap: "Single Step Potential"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}


\draw[, -{Stealth[length=2mm]}] (-3, 0) -- (4, 0) node [right] {$x$} ;
\draw[, -{Stealth[length=2mm]}] (0, 0) -- (0, 3) node [above] {$V(x)$};

\draw[teal, thick] (-3, 0) -- (0, 0) -- (0, 2) -- (3.5, 2);
\draw[teal, thick, dashed] plot[variable=\t, domain=-3:3, samples=100, smooth,thick] ({0.3*\t}, {2/(1+exp(-3*\t))});

\draw[{Stealth[length=2mm]}-{Stealth[length=2mm]}] (3,2) -- (3, 0);
\node[right] at (3, 1) {$V_0$};

\node[below] at (0, 0) {$O$};

\node at (-2, 0.5) {$\rm{I}$};
\node at (2, 0.5) {$\rm{II}$};

\end{tikzpicture}
```

</br>


```{r, engine = 'tikz'}
#| label: fig-part2_path_integral_1
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 4
#| fig-align: center
#| fig-cap: "Single Step Potential"


\begin{tikzpicture}[scale=2]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}


\draw[, -{Stealth[length=2mm]}] (-0.5, 0) -- (3, 0) node [right] {$t$} ;
\draw[, -{Stealth[length=2mm]}] (0, -0.5) -- (0, 3) node [above] {$x$};

\draw [blue, thick] plot [smooth, tension=0.7] coordinates { (0.4,0.4) (0.45, 0.55) (1,2) (2,2.7) (3,3)};
\draw [black, thick] plot [smooth, tension=0.7] coordinates { (0.4,0.4)  (1,1.2) (2,1.9) (3,3)};
\draw [teal, thick] plot [smooth, tension=0.7] coordinates { (0.4,0.4)  (1,0.5) (2.2,1.1) (3,3)};

\filldraw[black] (0.4, 0.4) circle (1pt) node[below] {$(x',t')$} ;
\filldraw[black] (3, 3) circle (1pt) node[above] {$(x,t)$} ;

\draw[blue, thick, -{Stealth[length=2mm]}] (2.1,2.75) -- (2.3, 2.83) node [above] {$x_\alpha(t)$} ;
\draw[black, thick, -{Stealth[length=2mm]}] (2.0,1.9) -- (2.2, 2.10) node [above, left] {$x_{cl}(t)$} ;

\draw[teal, thick, -{Stealth[length=2mm]}] (2.2,1.1) -- (2.4, 1.4) node [below right] {$x_\lambda(t)$} ;
\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_path_integral_2
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 4
#| fig-align: center
#| fig-cap: "Single Step Potential"


\begin{tikzpicture}[scale=2.5]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}


\draw[, -{Stealth[length=2mm]}] (-0.5, 0) -- (1.5, 0) node [right] {$t$} ;
\draw[, -{Stealth[length=2mm]}] (0, -0.5) -- (0, 1.5) node [above] {$x$};

\draw[thick, -{Stealth[length=2mm]}] (0, 0) -- (0.7, 0.7); \draw[thick] (0.5, 0.5) -- (1, 1) node [right] {$(1, 1)$};
\draw[teal, thick] plot[variable=\t, domain=0:1, samples=100, smooth,thick] ({\t}, {\t*\t});
\draw[teal, thick, -{Stealth[length=2mm]}] (0.65, 0.4225)--(0.7, 0.49);

\node [rotate=45] at (0.5, 0.7) {$x_{cl}(t)$};

\node [rotate=45] at (0.7, 0.3) {$x=t^2$};

\end{tikzpicture}
```

</br>
```{r, engine = 'tikz'}
#| label: fig-part2_path_integral_3
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 8
#| fig-align: center
#| fig-cap: "descrete approximation of path integral"


\begin{tikzpicture}[scale=1]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[, -{Stealth[length=2mm]}] (-0.2, 0) -- (10, 0) node [right] {$t$} ;
\draw[, -{Stealth[length=2mm]}] (0, -0.2) -- (0, 5) node [above] {$x$};

\foreach \x in {1, 2,..., 9}{
  \draw[] (\x, 4.7) -- (\x, 0);
}

\node[below] at (1, 0) {$t_0$};
\node[below] at (2, 0) {$t_1$};
\node[below] at (3, 0) {$t_2$};
\node[below] at (6, 0) {$t_i$};
\node[below] at (9, 0) {$t_N$};

\draw[thick,-{Stealth[length=2mm]}] (1, 0.7) node[left] {$x_0$}-- (1.5, 1.0); \draw[thick] (1.5, 1.0) -- (2, 1.3);
\draw[thick,-{Stealth[length=2mm]}] (2, 1.3) -- (2.5, 1.8); \draw[thick] (2.5, 1.8) -- (3, 2.3);
\draw[thick,-{Stealth[length=2mm]}] (3, 2.3) -- (3.5, 2.2); \draw[thick] (3.5, 2.2) -- (4, 2.1);
\draw[thick,-{Stealth[length=2mm]}] (4, 2.1) -- (4.5, 2.3); \draw[thick] (4.5, 2.3) -- (5, 2.5);
\draw[thick,-{Stealth[length=2mm]}] (5, 2.5) -- (5.5, 2.7); \draw[thick] (5.5, 2.7) -- (6, 2.9);
\draw[thick,-{Stealth[length=2mm]}] (6, 2.9) -- (6.5, 2.6); \draw[thick] (6.5, 2.6) -- (7, 2.3);
\draw[thick,-{Stealth[length=2mm]}] (7, 2.3) -- (7.5, 2.7); \draw[thick] (7.5, 2.7) -- (8, 3.1);
\draw[thick,-{Stealth[length=2mm]}] (8, 3.1) -- (8.5, 3.15); \draw[thick] (8.5, 3.15) -- (9, 3.2) node[right] {$x_N$};
\end{tikzpicture}
```



```{r, engine = 'tikz'}
#| label: fig-part2_1d_sho_wavefunction
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 8
#| fig-align: center
#| fig-cap: "descrete approximation of path integral"


\begin{tikzpicture}[scale=1.0]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[, -{Stealth[length=2mm]}] (-5, 0) -- (5, 0) node [right] {$x$} ;
\draw[, -{Stealth[length=2mm]}] (0, -0.2) -- (0, 11) node [above] {$E$};


\draw[teal, thick] plot[variable=\t, domain=-3.3:3.3, samples=100, smooth,thick] ({\t}, {\t*\t});


\draw[] plot[variable=\t, domain=-5:5, samples=100, smooth,thick] ({\t}, {0.751*exp(-(\t*\t)/2) + 1.0});
\draw[dashed] (-3, 1) -- (3, 1);
\node[above] at (4.5, 1) {$\Psi_0(x)$};

\draw[] plot[variable=\t, domain=-5:5, samples=100, smooth,thick] ({\t}, {0.531*exp(-(\t*\t)/2) *(2*\t) + 3.0});
\draw[dashed] (-3, 3) -- (3, 3);
\node[above] at (4.5, 3) {$\Psi_1(x)$};

\draw[] plot[variable=\t, domain=-5:5, samples=100, smooth,thick] ({\t}, {0.266 * exp(-(\t*\t)/2) *(-2*(1-2*\t*\t)) + 5.0});
\draw[dashed] (-3, 5) -- (3, 5);
\node[above] at (4.5, 5) {$\Psi_2(x)$};

\draw[] plot[variable=\t, domain=-5:5, samples=150, smooth,thick] ({\t}, {0.108 * exp(-(\t*\t)/2) *(-12*(\t-0.666*\t*\t*\t)) + 7.0});
\draw[dashed] (-4, 7) -- (4, 7);
\node[above] at (4.5, 7) {$\Psi_3(x)$};

\draw[] plot[variable=\t, domain=-5:5, samples=70,thick] ({\t}, {0.038 * exp(-((\t)^2)/2) *(12*(1-4*((\t)^2)+4/3*((\t)^4))) + 9.0});
\draw[dashed] (-4.5, 9) -- (4.5, 9);
\node[above] at (4.5, 9) {$\Psi_4(x)$};

\end{tikzpicture}
```

```{r, engine = 'tikz'}
#| label: fig-part2_identical_particles
#| code-fold: true
#| echo: fenced
#| output: asis
#| fig-width: 6
#| fig-align: center
#| fig-cap: "identical particle scattering"


\begin{tikzpicture}[scale=1.0]
\usetikzlibrary {arrows.meta}
\usetikzlibrary {calc}

\draw[thick] (0, 0)  -- (6, 0) -- (6, 8) -- (0, 8) -- cycle;
\node [below left] at (0, 0) {$1$};
\node [below right] at (6, 0) {$2$};
\node [above left] at (0, 8) {$3$};
\node [above right] at (6, 8) {$4$};

\draw[very thick, red] (0.5, 0) arc (0:90:0.5);
\draw[very thick,red] (5.5, 0) arc (180:90:0.5);
\draw[very thick,red] (6, 7.5) arc (270:180:0.5);
\draw[very thick,red] (0, 7.5) arc (270:360:0.5);

\filldraw[teal] (0.45, 0.6) circle (3pt) ;
\draw[dashed] (0.45, 0.6) -- (2.9, 4) -- (0.3, 7.6);
\filldraw[teal] (0.15, 7.8) circle (3pt) ;


\filldraw[teal] (5.55, 0.6) circle (3pt) ;
\draw[dashed] (5.55, 0.6) -- (3.1, 4) -- (5.7, 7.6);
\filldraw[teal] (5.85, 7.8) circle (3pt) ;

\node[above, scale=0.8] at (3, 0) {$t=0$};
\node[below, scale=0.8] at (3, 8) {$t=T$};

\end{tikzpicture}
```
