---
title: "고전적인 극한과 불확정성 원리"
number-sections: true
number-depth: 3
crossref:
  chapters: true
---

{{< include ../latexmacros.qmd >}}


## 에렌페스트 정리 {#sec-QM_ehrenfest_theorem}

양자역학의 거시적인 극한이 고전역학이어야 한다는 것은 당연하다. 여기서는 바로 이것에 다루기로 한다. 연신자 $\Omega$ 에 대한 양자역학의 기대값 $\langle \Omega\rangle$ 대해 다음이 성립한다.

$$
\dfrac{d}{dt}\langle \Omega \rangle = \dfrac{d}{dt} \langle \psi |\Omega |\psi\rangle = \langle \dot{\psi}|\Omega |\psi\rangle + \langle \psi |\dot{\Omega}| \psi \rangle + \langle \psi |\Omega |\dot{\psi}\rangle
$$ {#eq-QM_classica_limit_1}

여기서 $\Omega$ 에 명시적인 시간의존성이 없다고 가정하자. 즉 $\partial \Omega/\partial t = 0$ 라고 가정하자. 슈뢰딩거 방정식

$$
i\hbar |\dot{\psi}\rangle = H |\psi\rangle,\qquad  -i\hbar \langle\dot{\psi} | = \langle \psi |H
$$ {#eq-QM_classica_limit_2}

를 적용하면, 

$$
\dfrac{d}{dt}\langle \Omega \rangle = -\dfrac{i}{\hbar} \langle \psi | (-H\Omega + \Omega H)|\psi = -\dfrac{i}{\hbar} \langle \psi | [\Omega,\, H]|\psi \rangle
$$ {#eq-QM_classica_limit_3}

을 얻는다. 이를 **에렌페스트 정리(Ehrenfest's theorem)** 이라고 한다. 고전역학에서 동역학 변수 $\omega$ 와 해밀토니안 $H$, 그리고 푸아송 브라켓 $\{\,,\,\}$ 에 대해

$$
\dfrac{d\omega}{dt} = \{ \omega,\, H\} = \sum_i \left(\dfrac{\partial \omega}{\partial q_i}\dfrac{\partial H}{\partial p_i} -\dfrac{\partial \omega}{\partial p_i}\dfrac{\partial H}{\partial q_i}  \right)
$$

가 성립한다는 것을 기억하라. 

</br>

### 1차원 포텐셜의 경우

우선 1차원에서 생각해보자. 해밀토니안이 다음과 같다고 하자.

$$
H =\dfrac{P^2}{2m}+ V(X).
$$ {#eq-QM_classical_limit_1d_hamiltonian}

$\Omega=X$ 일 때 @eq-QM_classica_limit_3 은 다음과 같다.

$$
\dfrac{d}{dt}\langle X\rangle = -\dfrac{i}{\hbar} \langle \psi | [X,\, H]| \psi\rangle = \left(-\dfrac{i}{2m\hbar}\right) \langle [X,\,P^2]\rangle
$$ {#eq-QM_classical_limit_dot_x_1}

여기서

$$
[X,\,P^2]=P[X,\,P] + [X,\,P]P = 2i\hbar P
$$

이므로, 

$$
\dfrac{d}{dt}\langle X \rangle = \dfrac{\langle P\rangle}{m}
$$ {#eq-QM_classical_limit_dot_x_2}

이다. 고전역학의 $\dot{x} = p/m$ 를 기억하라. 

좀 다른 방식으로 접근해보자. @eq-QM_classical_limit_1d_hamiltonian 로 부터

$$
\dfrac{P}{m} = \dfrac{\partial H}{\partial P}
$$

임을 안다. 즉, 

$$
\dfrac{d}{dt}\langle X\rangle = \left \langle \dfrac{\partial H}{\partial P}\right \rangle
$$ {#eq-QM_classical_limit_dot_x_3}

이다. 이제 @eq-QM_classica_limit_3 에서 $\Omega = P$ 로 놓고 생각해보자.

$$
\dfrac{d}{dt} \langle P\rangle = \left(-\dfrac{i}{\hbar}\right) \langle [ P,\, H] \rangle = - \dfrac{i}{\hbar} \langle [P,\, V(X)]\rangle 
$$

이다. 우리는 $X$ 기저에서 $P$ 가 $-i\hbar \dfrac{d}{dx}$ 임을 안다. $V(X)$ 를 $V(x)$ 로 생각하면

$$
[P,\, V(x)]\psi(x) = \left[-i\hbar \dfrac{d}{dx},\, V(x)\right]\psi(x) = -i\hbar \left(\dfrac{dV(x)}{dx}\right)\, \psi(x)
$$

이므로, 

$$
\dfrac{d}{dt}\langle P\rangle = - \dfrac{dV(x)}{dx}= \left\langle -\dfrac{\partial H}{\partial X}\right\rangle
$$ {#eq-QM_classical_limit_dot_p}

이다. 식 @eq-QM_classical_limit_dot_x_3 과 @eq-QM_classical_limit_dot_p 은 해밀토니안 $\mathcal{H}$ 에 대한 고전적인 해밀튼 방정식 

$$
\dot{x} = \dfrac{\partial \mathcal{H}}{\partial p},\qquad\dot{q} = - \dfrac{\partial \mathcal{H}}{\partial q}
$$ {#eq-QM_classical_hamilton_equation}

와 매우 닮았다. 이제 양자역학의 방정식이 거시계에 어떻게 적용되는지 알아보기로 하자. 

</br>

### 거시시적인 계에서

일단 질량 $1\, \text{g}$ 인 입자를 생각하자. 고전적인 극한에서 생각해야 하기 때문에 입자의 위치와 운동량이 상대적으로 잘 정의된 가우시안 웨이브 패킷을 생각하자. 이 상태를 $|x_0\,p_0\,\Delta\rangle$ 로 표기하자. 이 패킷은 $\langle X\rangle = x_0$, $\langle P\rangle = p_0$, $\Delta X = \Delta,\, \Delta P \approx \hbar/\Delta$ 의 성질을 가진다고 하자. 그리고 $\Delta$ 와 $\hbar/\Delta$ 가 각각 거시계의 기준으로 매우 작다고 생각하자. 우리는 이미 [가우시안 wavepacket 의 시간 전개](QM_1d_bound_state.qmd#sec-evolution_of_gaussian_packet) 에서 이것이 가능함을 안다. 즉 아래의 $\Psi(x,\,0)$ 은 주어진 조건을 만족한다.

$$
\Psi(x,0) = e^{ip_0x/\hbar} \dfrac{e^{-(x-x_0)^2/2\Delta^2}}{(\pi \Delta^2)^{1/4}}.
$$

이 때 $\Delta \approx 10^{-15}\, \text{m}$ 이라고 하면(이 크기는 양성자의 크기와 유사하다) $\Delta P \approx 10^{-19}\, \text{kg m}/\text{sec}$ 이다. $m=1\, \text{g}$ 일 경우 속도의 uncertainty $\Delta V \approx 10^{-16}\, \text{m}/\text{sec}$ 이므로 실험에서 측정 할 수 있는 정밀도보다 크게 작다. 이 경우 거시적으로는 위치와 운동량이 $x_0,\, p_0$ 로 잘 정의되어 있다고 볼 수 있다. @eq-QM_classical_limit_dot_x_3 와 @eq-QM_classical_limit_dot_p 에서 $\langle \cdots \rangle$ 은 함수에 대한 평균인데 이것을 평균에 대한 함수로 바꾼다면 고전적인 해밀튼 방정식 @eq-QM_classical_hamilton_equation 와 같아진다. 


$$
\begin{aligned}
\dot{x}_0 &= \dfrac{d}{dt}\langle X \rangle = \left \langle \dfrac{\partial H}{\partial P}\right \rangle  \approx \left.\dfrac{\partial H}{\partial P}\right|_{X=x_0,\, P=p_0} = \dfrac{\partial \mathcal{H}(x_0,\, p_0)}{\partial p_0} \\[0.4em]
\dot{p}_0 &= \dfrac{d}{dt}\langle P\rangle = - \left\langle \dfrac{\partial H}{\partial X}\right\rangle \approx \left.\dfrac{\partial H}{\partial X}\right|_{(X=x_0,\, P=p_0)}  = - \dfrac{\partial \mathcal{H}(x_0,\, p_0)}{\partial x_0}
\end{aligned}
$$

이제 $X$ 와 $P$ 의 함수로 주어지는 어떤 연산자 $\Omega$ 의 고전적인 대응인 $\omega (x,\,p)$ 를 생각하자. $X,\, P$ 가 충분히 잘 정의되어 있다면(즉 $\Delta X$ 와 $\Delta P$ 가 충분히 작다면) 다음이 성립한다는 것을 예상 할 수 있다.

$$
\langle \Omega (X,\, P) \rangle \approx \Omega (x_0,\, p_0) = \omega(x_0,\,p_0)
$$

그렇다면 이제 다음 관계를 끌어 낼 수 있다.

$$
\left\langle \dfrac{\partial H}{\partial X}\right \rangle = \left \langle\dfrac{dV}{dX} \right\rangle \approx  \left.\dfrac{dV}{dx}\right|_{X=x_0}
$$

여기에 $V'(x)$ 에 대한 테일러 전개를 생각하자.

$$
V'(x) = V'(x_0) + V''(x_0)(x-x_0) + \dfrac{1}{2} V'''(x_0)(x-x_0)^2 + \cdots
$$

그렇다면 $\langle X-x_0\rangle =0$ 이므로

$$
\left\langle \dfrac{\partial H}{\partial X}\right \rangle \approx V'(x_0) + \dfrac{1}{2} V'''(x_0) (\Delta X)^2
$$

이 될 것이다. $\langle \partial H/\partial X\rangle = V'(x_0)$ 는 고전적인 뉴턴 방정식의 결론이다. 양자역학에서는 여기에 high order term 이 도입되는데 이것은 양자의 입자는 자신의 위치 분만 아니라 주변의 영향($(\Delta X)^2$) 도 받는다는 것을 의미한다. 물론 $\Delta X$ 가 매우 작고 $V(X)$ 가 천천히 변한다면 이 효과는 거의 무시할만 해 진다. 그러나 양자적인 효과를 고려해야 할 몇가지 경우를 생각해보자.

</br>

#### **Wave packet spreading**

가우시안 패킷은 시간이 지남에 따라 $\Delta X$ 가 커진다. @exm-macroscopic_propagation 에서 보았듯이 $\Delta X=10^{-15}\,\text{m}$, $\Delta P \approx 10^{19} \, \text{kg m}/\text{sec}$ 인 경우 wave packet 이 퍼져서 $\Delta X\approx 1.0\times 10^{-3}\, \text{m}= 1 \, \text{mm}$ 가 되는데 $400,000$ 년 이상 걸리긴 하지만 말이다. 

</br>

## 하이젠베르그의 불확정성 원리

### 불확정성 {#sec-QM_uncertainty}

고전역학에서의 상태는 위치 $\bf{x}$ 와 운동량 $\bf{p}$ 에 의해 결정되며 상태가 $(\bf{x}_0,\, \bf{p}_0)$ 로 정해졌다면 어떤 동역학 변수 $\omega(\bf{x},\, \bf{p})$ 에 대해서도 $\omega(\bf{x}_0,\, \bf{p}_0)$ 의 정해진 값을 가진다. 그러나 양자역학에서는 주어진 상태 $|\Psi\rangle$ 에 대해 $\Omega$ 측정을 했을 때의 값은 확률로 주어진다. 그리고 확률 분포는 기대값, 즉 평균값 $\langle \Omega \rangle = \langle \Psi |\Omega |\Psi \rangle$ 과 불확정도(uncertainty), 즉 표준편차 $\Delta \Omega$ 에 의해 특정지어진다.

$|\Psi\rangle$ 이 $\Omega$ 의 고유상태로 고유값 $\omega$ 를 가진다면 $\Omega |\Psi\rangle = \omega |\psi \rangle$ 이며 따라서 $\Delta \Omega = 0$ 이다.

두 에르미트 연산자 $\Omega,\, \Lambda$ 를 생각하자. 임의의 상태에 대해 두 연산자에 대한 불확정도 $\Delta \Omega$ 와 $\Delta \Lambda$ 를 생각 할 수 있다. 여기서는 하이젠베르그의 불확정성의 원리에 대해 알아볼 것이다. 이 불확정성의 원리는 두 불확정도의 곱 $\Delta \Omega \cdot \Delta \Lambda$ 의 하한을 정한다. 일반적으로 이 하한은 상태 뿐만 아니라 연산자에 의존한다. 또한 어떤 경우에는 이 불확정성이 상태에 무관하개 정해지기도 한다. 이 불확정성을 유도하는 과정에서 이런 관계가 존재하는 조건을 명확하게 할 할 것이다.

</br>

### 불확정성의 유도 {#sec-QM_derivation_of_uncertainty_relation}

두 에르미트 연산자 $\Omega,\, \Lambda$ 의 교환관계가 다음과 같다고 하자.

$$
[\Omega,\, \Lambda] = i\Gamma.
$$ {#eq-QM_uncertainty_nonzero_commutator}

이 때 $\Gamma$ 역시 에르미트 연산자임을 보일 수 있다.
$$
\Gamma^\dagger = \left((-i)[\Omega,\, \Lambda]\right)^\dagger = i(\Omega \Lambda - \Lambda\Omega)^\dagger = i(\Lambda \Omega - \Omega \Lambda) = \Gamma.
$$

임의의 정규화된 상태 $|\Psi\rangle$ 에 대해, 그리고 코시-슈바르츠 부등식을 이용하면

$$
\begin{aligned}
(\Delta \Omega)^2 (\Delta \Lambda)^2 &= \langle \Psi |(\Omega -  \langle \Omega\rangle )^2|\Psi\rangle \langle \Psi |(\Lambda - \langle \Lambda \rangle)^2|\Psi\rangle \\[0.3em]
&= \langle (\Omega - \langle \Omega \rangle)\Psi| (\Omega - \langle \Omega \rangle)\Psi\rangle \langle (\Lambda - \langle \Lambda \rangle)\Psi| (\Lambda - \langle \Lambda \rangle)\Psi\rangle \\[0.3em] 
&\ge \left|\langle (\Omega - \langle \Omega \rangle)\Psi| (\Lambda - \langle \Lambda \rangle)\Psi\rangle \right|^2 \\[0.3em]
&= \left|\langle \Psi |(\Omega -\langle \Omega \rangle)(\Lambda - \langle \Lambda \rangle) |\Psi\rangle\right|^2
\end{aligned}
$$ {#eq-QM_uncertainty_derivation_of_uncertianty_relation_1}

을 얻는다. 

임의의 연산자 $A,\,B$ 에 대해 

$$
AB = \dfrac{AB+BA}{2}+ \dfrac{AB-BA}{2} = \dfrac{1}{2} \left\{ A,\, B\right\} + \dfrac{1}{2} [A,\,B]
$$

이다. 여기서 $\{A,\,B\}:=AB+BA$ 는 푸아송 브라킷(Poisson bracket), 혹은 anticommutator 라고 불린다. 또한 $A,\,B$ 가 에르미트 연산자라면 $\{A,\,B\}$ 역시 에르미트 연산자임을 보일 수 있다.

$$
(\{A,\,B\})^\dagger = (AB+BA)^\dagger = (AB+BA) = \{A,\,B\}
$$


$A=\Omega -\langle \Omega \rangle$, $B=\Lambda - \langle \Lambda \rangle$ 이라고 하자. $\Omega,\, \Lambda$ 가 에르미트 연산자이므로 $A,\,B$ 역시 에르미트 연산자이다. 또한,

$$
\begin{aligned}
\;[A,\,B] &= [\Omega -\langle \Omega \rangle,\, \Lambda -\langle \Lambda \rangle] = [\Omega,\, \Lambda] = i\Gamma
\end{aligned}
$$

임을 알 수 있다. @eq-QM_uncertainty_derivation_of_uncertianty_relation_1 로부터

$$
\begin{aligned}
(\Delta \Omega)^2 (\Delta \Lambda)^2 \ge \left|\langle \Psi|AB|\Psi \rangle\right|^2 &= \dfrac{1}{4}\left|\langle \Psi | \{A,\,B\} + [A,\,B]|\Psi\rangle \right|^2 \\[0.3em]
&= \dfrac{1}{4}\left|\langle \Psi | \{A,\,B\} |\Psi\rangle+ i \langle \Psi|\Gamma |\Psi|\rangle\right|^2
\end{aligned}
$$

임을 안다. $\{A,\,B\}$ 와 $\Gamma$ 가 에르미트 연산자이므로 

$$
(\Delta \Omega)^2 (\Delta \Lambda)^2 \ge \dfrac{1}{4} \langle \Psi|\{\Omega - \langle \Omega \rangle,\, \Lambda - \langle \Lambda \rangle\}|\Psi\rangle^2 + \dfrac{1}{4}\langle \Psi |\Gamma |\Psi \rangle^2
$${#eq-QM_uncertainty_derivation_of_uncertianty_relation_2}

이다. $\{\cdots \}$ 관련 항은 항상 양수이며 $[\Omega,\, \Gamma] = i\Gamma$ 이므로

$$
(\Delta \Omega)(\Delta \Gamma) \ge \dfrac{1}{2}|\langle \Psi |\Gamma |\Psi\rangle|
$$ {#eq-QM_uncertianty_uncertainty_relation}

이 성립한다. 이를 불확정성 관계라고 한다. 위 식에서 등식이 성립하는 경우는 아래의 두 조건을 모두 만족하는 경우 뿐이다.

$$\begin{aligned}
&(1)&& \langle \Psi|\{\Omega - \langle \Omega \rangle,\, \Lambda - \langle \Lambda \rangle\}|\Psi\rangle=0,\\[0.3em]
&(2)&&\exists c\in \C,\, \text{s. t. } (\Omega - \langle \Omega)|\Psi\rangle = c(\Lambda - \langle \Lambda \rangle)|\Psi\rangle.
\end{aligned}
$${#eq-QM_uncertianty_uncertainty_relation_2}

여기서 $(1)$ 조건은 @eq-QM_uncertainty_derivation_of_uncertianty_relation_1 의 코시-슈바르츠 부등식 조건으로 부터 나온다.


</br>

### 불확정성을 최소화 하는 패킷 {#sec-QM_uncertainty_minimum_uncertainty_packet}


$X,\,P$ 의 불확정성을 최소화 하는 1차원 파동함수 $\Psi(x)$ 를 구해보자. @eq-QM_uncertianty_uncertainty_relation_2 의 $(2)$ 로부터,

$$
(P-\langle P\rangle) |\Psi\rangle = c(X-\langle X\rangle)|\Psi\rangle
$$ {#eq-QM_uncertainty_minimal_packet_1}

이어야 한다. $X$ 기저에서 아래와 같은 미분방정식이다.

$$
\left(- i\hbar\dfrac{d}{dx} - \langle P\rangle\right) \Psi(x) = c(x-\langle X\rangle)\Psi(x)
$$

를 만족해야 한다. 일반성을 잃지 않고 $\langle X \rangle = 0$ 으로 놓을 수 있다. 그렇다면 이 방정식의 해는
$$
\Psi(x) = \Psi(0) e^{i\langle P\rangle x/\hbar} e^{icx^2/2\hbar}
$${#eq-QM_uncertainty_minimal_packet_2}

이다. 이제 @eq-QM_uncertianty_uncertainty_relation_2 의 $(1)$ 를 생각하자. 그리고 $\langle X\rangle = 0$ 을 다시 이용하면 $|\Psi\rangle$ 은 아래 식을 만족해야 한다.

$$
\begin{aligned}
&\langle \Psi | (P-\langle P\rangle) X + X(P-\langle P\rangle) |\Psi\rangle = 0.
\end{aligned}
$$

@eq-QM_uncertainty_minimal_packet_1 의 adjoint 는

$$
\langle \Psi | (P-\langle P\rangle) = c^\ast \langle \Psi |(X-\langle X\rangle)
$$

이므로, 

$$
\langle \Psi |c^\ast X^2 + cX^2|\Psi\rangle = 0
$$

을 얻는다. 즉

$$
(c+c^\ast) \langle \Psi|X^2|\Psi\rangle = 0
$$

이다. $c = i\alpha$ ($\alpha \in \mathbb{R}$) 라고 놓자. 그렇다면 @eq-QM_uncertainty_minimal_packet_2 는 아래와 같이 쓸 수 있다.

$$
\Psi(x) = \Psi(0) e^{i\langle P\rangle x/\hbar} e^{-\alpha x^2/2\hbar}.
$${#eq-QM_uncertainty_minimal_packet_3}

여기서 $\alpha > 0$ 이어야 $\Psi(x)$ 가 정규화 가능하다. 이 파동함수는 가우시안 형태를 가지며, $X$ 와 $P$ 의 불확정성을 최소화하는 상태를 나타낸다. 이를 **최소 불확정성 패킷(minimum uncertainty packet)** 이라고 한다. 

</br>

### 불확정성의 원리의 응용 {#sec-QM_uncertainty_uncertainty_principle}

이제 불확정성의 원리를 사용하여 바닥상태 에너지와 바닥상태 패동함수의 분포에 대해 알아 볼 수 있다. 수소원자의 경우를 생각해보자. 수소원자에서 양성자를 고정시켰을 때의 해밀토니안은 다음과 같다.

$$
H = \dfrac{P_x^2+P_y^2+P_z^2}{2m} - \dfrac{e^2}{(X^2+Y^2+Z^2)^{1/2}}
$$

정규화된 상태 $|\Psi\rangle$ 에서

$$
\langle H \rangle = \dfrac{\langle P_x^2\rangle +\langle P_y^2\rangle+\langle P_z^2\rangle}{2m} - e^2 \left\langle \dfrac{1}{(X^2+Y^2+Z^2)^{1/2}}\right\rangle
$$

이다. $\langle P_i^2\rangle = (\Delta P_i)^2 + \langle P_i\rangle^2$ 이며 $\langle P_i\rangle =0$ 으로 놓고 시작해 보자.

$$
\langle H\rangle = \dfrac{ (\Delta P_x)^2 +  (\Delta P_y)^2+ (\Delta P_z)^2}{2m} - e^2 \left\langle \dfrac{1}{(X^2+Y^2+Z^2)^{1/2}}\right\rangle
$$

이다. 우리는 $\Delta P_x \Delta X \ge \hbar/2$ 임을 안다. 문제는 $\langle (X^2+Y^2+Z^2)^{-1/2}\rangle$ 이 $\Delta X,\, \Delta Y,\, \Delta Z$ 와 단순하게 관련되지 않는다는 것이다. 일단 아래와 같이 장난을 해 보자.

$$
\left\langle \dfrac{1}{(X^2+Y^2+Z^2)^{1/2}}\right\rangle \simeq \dfrac{1}{\langle (X^2+Y^2+Z^2)^{1/2}\rangle}
$$

그렇다면

$$
\langle H \rangle \simeq  \dfrac{(\Delta P_x)^2 +  (\Delta P_y)^2+ (\Delta P_z)^2}{2m} -e^2\dfrac{1}{\langle (X^2+Y^2+Z^2)^{1/2}\rangle}
$$

이다. 운동량과 마찬가지로 $\langle X^2+Y^2+Z^2\rangle \simeq (\langle X^2\rangle +\langle Y^2\rangle + \langle Z^2\rangle)^{1/2}$ 라고 놓으면

$$
\langle H \rangle \simeq  \dfrac{(\Delta P_x)^2 +  (\Delta P_y)^2+ (\Delta P_z)^2}{2m} -e^2\dfrac{1}{(\langle X^2\rangle +\langle Y^2\rangle + \langle Z^2\rangle)^{1/2}}
$$

역시 $\langle X^2\rangle = (\Delta X)^2 + \langle X\rangle^2$ 의 관계를 생각하자. $\langle X\rangle = \langle Y \rangle = \langle Z\rangle = 0$ 인 상태로 한정하고 가장 낮은 에너지를 찾아보자. 이 경우

$$
\langle H \rangle \simeq \dfrac{(\Delta P_x)^2 +  (\Delta P_y)^2+ (\Delta P_z)^2}{2m} - \dfrac{e^2}{((\Delta X)^2+(\Delta Y)^2+ (\Delta Z)^2)^{1/2}}
$$

이다. 그런에 수소 원자 문제는 구면 대칭 문제이다. 이 경우 파동함수가 구면 대칭일 경우 가장 낮은 에너지를 가질것이라는 것이 직관적으로 명백하다. 즉 

$$
(\Delta X)^2 = (\Delta Y)^2 = (\Delta Z)^2,\qquad (\Delta P_x)^2 = (\Delta P_y)^2 = (\Delta P_z)^2
$$

의 경우에 가장 낮은 에너지를 가질 것이다. 그렇다면,

$$
\langle H \rangle \simeq \dfrac{3(\Delta P_x)^2}{2m} - \dfrac{e^2}{\sqrt{3}(\Delta X)}
$$

이다. 여기에 불확정성의 원리 $\Delta P_x \Delta X \ge \hbar /2$ 를 적용하면

$$
\langle H \rangle \ge \dfrac{3\hbar^2}{8m (\Delta X)^2} - \dfrac{e^2}{\sqrt{3}(\Delta X)}
$$

이며 미분을 통해 가장 낮은 에너지를 가지는 $\Delta X$ 를 구하면

$$
\Delta X = \dfrac{3\sqrt{3}\hbar^2}{4me^2} \approx 1.3 \dfrac{\hbar^2}{me^2}
$$

이며,

$$
\langle H \rangle \ge \dfrac{-2me^4}{9\hbar^2}
$$

이다. 뒤에 구하겠지만 실제 수소원자의 바닥상태 에너지 $E_g = \dfrac{-me^4}{2\hbar^2}$ 이다. 약 2.25 배 차이가 난다. 그리고 우리는 불확정성을 최소로 하는 파동함수, 즉 가우시안 파동함수를 가정했지만 실제 파동함수는 가우시안 파동함수가 아니라

$$
\Psi(r) = ce^{-r/a_0},\qquad a_0 = \dfrac{\hbar^2}{me^2}
$$

이다. 이 때의 $a_0$ 를 **보어 반지름 (Bohr radius)** 라고 한다.

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-QM_shankar_9_4_1}
#### Shankar 9.4.1

뒤의 단순조화진동자에서 $|n=1\rangle$ 상태에 대해

$$
\left \langle \dfrac{1}{X^2}\right \rangle \simeq \dfrac{1}{\langle X^2\rangle} \simeq \dfrac{m\omega}{\hbar}
$$

임을 보여라.

:::

</div></br>

::: {.solution}

@eq-QM_sho_xi, @eq-QM_sho_energy_eigenstate_with_hermite_polynomial, @eq-QM_sho_hermite_polynomial_first_4 를 생각하자. $\alpha = \sqrt{m\omega/\hbar}$ 라고 하면 $\xi = \alpha x$ 이며,
$$
\begin{aligned}
\left \langle \dfrac{1}{X^2}\right \rangle &= \left(\dfrac{m\omega}{4\pi \hbar}\right)^{1/2} \int_{-\infty}^\infty \dfrac{1}{x^2} (4\alpha^2x^2) e^{-\alpha^2x^2} \, dx \\
&=  \left(\dfrac{m\omega}{4\pi \hbar}\right)^{1/2} 4\alpha^2 \int_{-\infty}^\infty e^{-\alpha^2x^2} \\
&=  \left(\dfrac{m\omega}{4\pi \hbar}\right)^{1/2} 4\sqrt{\pi} \alpha =\dfrac{2m\omega}{\hbar}
\end{aligned}
$$

또한 @eq-QM_sho_x_and_p_with_ladder_operator_3 로부터 $\langle 1|X^2 |1\rangle = \dfrac{3\hbar}{2m\omega}$ 이므로

$$
\dfrac{1}{\langle X^2\rangle} = \dfrac{2m\omega}{3\hbar}
$$
이다. 

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-QM_shankar_9_4_2}
#### Shankar 9.4.2

($1$) 아래의 파동함수는 수소원자의 바닥상태의 그것이다. 이 파동함수가 정규화되어 있다는 것을 보여라.

$$
\Psi(r) = \dfrac{1}{\sqrt{\pi a_0^3}}e^{-r/a_0},\qquad r=\sqrt{x^2+y^2+z^2}.
$$

($2$) 이 파동함수의 $(\Delta X)^2$ 를 계산하고 $\Delta X = \dfrac{\hbar^2}{me^2}$ 임을 보여라. 이를 위해 $(\Delta X)^2 = \dfrac{1}{3}\langle r^2 \rangle$ 임을 논하라.

($3$) 이 경우 $\langle 1/r \rangle \simeq 1/\langle r \rangle \simeq me^2/\hbar^2$ 임을 보여라.


:::

</div></br>

::: {.solution}

($1$) $\displaystyle \int_0^\infty r^{n}e^{-\alpha r}\, dr = \dfrac{n!}{a^{n+1}}$ 임을 이용한다. 
$$
\begin{aligned}
\langle \Psi|\Psi \rangle &= \dfrac{1}{\pi a_0^3} \int_0^{2\pi} \int_0^\pi \int_0^\infty e^{-2r/a_0} r^2 \sin \theta \, dr d\theta d\varphi = \dfrac{4}{a_0^3} \int_0^\infty r^2 e^{2r/a_0}\,dr =1
\end{aligned}
$$


($2$) $r^2 = X^2 + Y^2+ Z^2$ 이며 수소원자의 원자핵의 위치를 원점으로 잡자. $\Psi(r)$ 이 구면대칭이므로 $\langle X \rangle  = \langle Y \rangle = \langle Z \rangle = 0$ 이고 $(\Delta X)^2 = (\Delta Y)^2 = (\Delta Z)^2$ 이다. 따라서

$$
3(\Delta X)^2 = \langle X^2+Y^z+Z^2 \rangle = \langle r^2\rangle
$$

이다. 

$$
(\Delta X)^2 = \dfrac{1}{3}\langle r^2\rangle =  \dfrac{1}{3\pi a_0^3} \int_0^{2\pi} \int_0^\pi \int_0^\infty e^{-2r/a_0} r^4 \sin \theta \, dr d\theta d\varphi = \dfrac{4}{3a_0^3} \dfrac{4!}{(2/a_0)^5} = a_0^2
$$

($3$)

$$
\left \langle \dfrac{1}{r}\right \rangle = \dfrac{1}{\pi a_0^3} \int_0^{2\pi} \int_0^\pi \int_0^\infty e^{-2r/a_0} r \sin \theta \, dr d\theta d\varphi = \dfrac{4}{a_0^3}\dfrac{a_0^2}{4} = \dfrac{1}{a_0}= \dfrac{me^2}{\hbar^2}
$$

이며

$$
\langle r \rangle = \dfrac{1}{\pi a_0^3} \int_0^{2\pi} \int_0^\pi \int_0^\infty e^{-2r/a_0} r^3 \sin \theta \, dr d\theta d\varphi = \dfrac{4}{a_0^3} \dfrac{3!}{(2/a_0)^4}= \dfrac{3a_0}{2} 
$$

이므로

$$
\dfrac{1}{\langle r \rangle} = \dfrac{2}{3a_0} = \dfrac{2me^2}{3\hbar^2}
$$

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-QM_shankar_9_4_3}
#### Shankar 9.4.3

수소 원자가 3차원 시스템이라는 것을 잊고 다음과 같은 1차원 시스템이라고 생각하자.

$$
H = \dfrac{P^2}{2m}- \dfrac{e^2}{(R^2)^{1/2}},\qquad (P^2=P_x^2+P_y^2+P_z^2,\; R^2=X^2+Y^2+Z^2).
$$

$\Delta P \cdot \Delta R \ge \hbar/2$ 라고 가정하고 바닥상태 에너지를 가늠하라.

:::

</div></br>

::: {.solution}

$\langle P \rangle = 0,\, \langle R \rangle =0$ 이라고 놓자. $\langle P^2 \rangle = (\Delta P)^2$, $\langle R^2 \rangle = (\Delta R)^2$ 이며 또한 $\langle 1/\sqrt{R^2} \rangle = 1/(\Delta R)$ 로 놓는다.
$$
\langle H\rangle =  \dfrac{\langle P^2\rangle }{2m}- \left \langle \dfrac{e^2}{ (R^2)^{1/2}} \right \rangle \simeq \dfrac{(\Delta P)^2}{2m} - \dfrac{e^2}{\Delta R}\ge \dfrac{\hbar^2}{8m(\Delta R)^2} - \dfrac{e^2}{(\Delta R)}
$$

이며 이 부등식의 최소값은 $(\Delta R) = \dfrac{\hbar^2}{4me^2}$ 일 때 이므로

$$
H \ge \dfrac{2me^4}{\hbar^2} - \dfrac{4me^4}{\hbar^2} = - \dfrac{2me^4}{\hbar^2}
$$

이다. 즉 이렇게 수소원자의 바닥상태의 에너지를 가늠하면 $-\dfrac{2me^4}{\hbar^2}$ 이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-QM_shankar_9_4_4}
#### Shankar 9.4.4

$T=\dfrac{P^2}{2m}$ 에 대해 $\Delta T \cdot \Delta X$ 를 구하라. 왜 이 관계는 유명하지 않을까?

:::

</div></br>

::: {.solution}
@eq-QM_uncertainty_derivation_of_uncertianty_relation_2 을 생각하자. 우선
$$
[T,\,X] = \dfrac{1}{2m}[P^2,\, X]= \dfrac{1}{2m}\left(P[P, X] - [X, P] P\right) = - \dfrac{i\hbar}{m}P
$$

이다. 
$$
(\Delta T)\cdot (\Delta X) \ge \dfrac{\hbar}{2m}|\langle P \rangle|
$$

의 관계가 성립한다. $T$ 와 $X$ 사이의 불확실성이 $P,\,X$ 와 다르게 상수가 아닌 $\langle P\rangle$ 에 의존하므로 별로 유명하지 않은 것 같다.


:::


</br>

### 에너지-시간 불확정성 {#sec-QM_uncertainty_energy_time}

<!-- 에너지와 시간에 관한 아래와 같은 불확정 관계가 존재한다.

$$
\Delta E \cdot \delta t \ge \dfrac{\hbar}{2}.
$$ {#eq-QM_uncertianty_energy_time}

위 관계는 일단 @eq-QM_uncertainty_derivation_of_uncertianty_relation_2 와는 다른데 시간은 동역학 변수가 아니라 parameter 이기 때문이다. 즉 위의 불확정 관계는 우리가 이전에 다루었던 동역학 변수 사이에서의 불확정성과는 근원이 다르다. @eq-QM_uncertianty_energy_time 의 의미를 대략적으로 설명하면 유한한 시간 $\delta t$ 동안 존재하는 시스템의 에너지는 최소한 $\Delta E$ 만큼의 불확정성이 존재한다는 의미이다.

에너지 $E$ 에 대한 고유상태는 슈뢰딩거 방정식에 따라 $e^{iEt/\hbar}$ 의 시간의존성을 가진다. 즉 에너지 $E$ 는 정해진 각진동수 $\omega = E/\hbar$ 의 성질을 갖게 된다. 만약 어떤 유한한 시간동안만 어떤 상태에 있을 수 있는 시스템이 있다면 이 시스템은 잘 정의된 각진동수를 가질 수 없으며, 따라서 에너지 역시 잘 정의되지 않을 것이다.  -->

...

에너지 시간 불확정성에 대해서는 생각보다 많은 오류/논의/불일치가 존재한다. 

see [Uncertainty principle in Wikipedia](https://en.wikipedia.org/wiki/Uncertainty_principle#Energy–time)